### ISSUE TITLE
Cannot set correct permissions for different contexts

### ISSUE THREAD

**Issue by ghost** [modxbot/migrate#10422]
stetus created Redmine issue ID 10422

When having 2 (or more) contexts, you cannot give one user-group permission to have full permission on the first context and have different rights (e.g. read-only) on the other. Steps to reproduce:
-) create 2 contexts
-) create user group & member
-) create limited access policy
-) "user group" -> "context access": set access policy "Administrator" for context A and the limited access policy for B

**Comment by splittingred** [comment]
splittingred submitted:

I had no issues doing this, can you detail specifically (with each step) what you tried to do and what the error was?

**Comment by ghost** [comment]
stetus submitted:

Thanks for your answer. Let's pretend you've just installed a standard MODx-System and you're logged in as an administrator. Create a new user (I call him „testuser“)
Create a new usergroup (I call it „testgroup“), assign testuser to that group. Create a new context („testcontext“). Duplicate administrator-policy („Duplicate of Administrator“), remove permissions „create“, „delete_context“, „publish_document“, and „save“. Give administrator-group access to testcontext, minimum role „superuser“, access policy „Administrator“ (Administrator is a „Super User“). Update usergroup „testgroup“, give context access to mgr, minimum role „member“, access policy „Duplicate of Administrator“. Add context access to web, minimum role „member“, access policy „Load, List and View“. Add context access to „testcontext“, minimum role „member“, access policy „Administrator“. After doing this, I can't create resources anywhere (not even if I add „create“ to the „Duplicate of Administrator“-policy). I tried around with the policies a lot, but I see no way to give different rights for different contexts, it just doesn't work. I used a fresh, brand-new installation to test. Thanks a lot for having an eye on that issue.

**Comment by splittingred** [comment]
splittingred submitted:

Of course you can't save anywhere - you removed the 'create' and 'save' Permissions. You need those to create and save objects. If you're wanting to prevent saving or creating of a Document, you should use `save_document` and `new_document`.

**Comment by ghost** [comment]
stetus submitted:

Thanks for your answer Shaun, of course you're right - when I add 'create' and 'save' permissions, it is possible to create and save objects again - but that doesn't solve the problem.
The permission settings for 'mgr' seem to overwrite the ones for the contexts, so there is no way to set different permissions for different contexts.

**Comment by opengeek** [comment]
opengeek submitted:

Context Policies (e.g. Administrator) and their permissions apply to all actions taken "from a specified context", not to a specified context. IOW, if you tried to execute a processor from a context like web, then your Context policy permissions would be applied to the web context, not when editing Resources in the web context from the mgr context; that is still the policy applied to mgr. In fact, be careful, by applying these Policies to a Context other than mgr, you are making it possible for snippets to execute manager actions in those Contexts. What you are wanting is not really possible currently; which is to apply different Policy permissions within the mgr context when working with Resources belonging to a specific Context. Since Resources can theoretically live in multiple Contexts, this is going to be a can of worms, and I think the proper solution to this long term is to be able to easily apply Resource Group policies from the root of a Context (i.e. Resource id = 0) without having to add every single Resource in the Context to the Resource Group.

**Comment by opengeek** [comment]
opengeek submitted:

This was the result of a misunderstanding of policies which target Context ACLs; these serve to define what actions can be taken from a specific Context, not to a specific front-end Context from within the mgr.
