### ISSUE TITLE
Parser return tag unaltered if the element doesn't exist

### ISSUE THREAD

**Issue by rickj** [modxbot/migrate#10465]
rickj created Redmine issue ID 10465

When the modx parser attempts to parse a tag (or something it mistakes for a tag) and it can't find an element corresponding to the tag name, it eats the tag and returns nothing. I suggest it return the tag unaltered. Admittedly, not often will a page have text with [[, but if the parser is extended to use simpler tags (which someone will eventually attempt), false positives would increase. As it is, someone had a false match with an encoded email address here: http://modxcms.com/forums/index.php/topic,53829.0.html Could the processTag() method of the modParser class be modified to return $outerTag instead of a null $elementOutput if the element doesn't exist?

**Comment by splittingred** [comment]
splittingred submitted:

Leaving it so it strips it; not stripping it could lead to: Vulnerability exposures, as that would allow people to see all unexecuted snippets, therefore setting what extras are installed Break a commonly used method of doing [ &#91;Comment my comments here since this wont execute &#93; ] that many MODx users do Cause unwanted behavior that is a deviant of the MODx standard since its beginning. Sorry!
