### ISSUE TITLE
Default values not set for complex TV input strings

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1047]
bobray created Redmine issue ID 1047

Not sure if this is a bug or an improvement. I don't know what Evo does. For this input string 1==Red||2==Green||3==Blue default values must be set to Red, Green, or Blue. Setting the default to 1, 2, or 3, doesn't work. This could be fairly inconvenient when the right side is a long string. a path or a URL.as they often are. Would need to be fixed for checkboxes, radio options, and DD-lists.

**Comment by splittingred** [comment]
splittingred submitted:

More of a feature request, since by most paradigms, defaultValue represents the default value , not the default key. Here you're wanting by default key; this could get very problematic if there's a key that matches a value, or vice versa, and isn't the normal expected behavior for a 'default value'.

**Comment by BobRay** [comment]
bobray submitted:

I still think this would be a good improvement.
