### ISSUE TITLE
Duplicating a TV shouldn't duplicate its values in resources (should it?)

### ISSUE THREAD

**Issue by jrotering** [modxbot/migrate#10489]
jrotering created Redmine issue ID 10489

http://modxcms.com/forums/index.php?topic=53158 I did a "duplicate" on a TV that already was in use on several resources. I only wanted a quick way to set up a similar TV w/ same category, input type, output type & template access. I was pretty surprised that this actually copied the old TV's value to the new TV for every resource. I'm not sure if this is a bug, or a feature, or just a topic that needs clarification and expectation-adjustments. A TV is a different kind of animal than a snippet, chunk or plugin. Maybe TV duplication should behave the way it currently does. Or maybe an option should be added: "copy TV values in resources". At any rate, I'm going on record as one MODx user who at least once had the need to duplicate a TV without duplicating its values in resources.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in http://github.com/modxcms/revolution/commit/6cb364c75161e2345de4cc5dd9925cd3b380be68 You can now specify if you want to duplicate the values in the duplicate window (when right-click duplicate element in the elements tree). Default behavior is to not dupe the values.
