### ISSUE TITLE
do not work with php_wincache

### ISSUE THREAD

**Issue by samz** [modxbot/migrate#10561]
samz created Redmine issue ID 10561

extension=php_wincache.dll version 1.1
500 error in manager hapens very offen and sametime in other pages.
evolution works fine(faster 500%-1000%) with php_wincache
ofter disabling extension everything ok.

**Comment by opengeek** [comment]
opengeek submitted:

I don't know where to start on this. Do we have any ideas on why this could be happening? It works perfect with eAccelerator and APC since they both fixed a bug with being unable to reload classes from cache when multiple classes existed in a single file. Could this be an overlooked issue in php_wincache perhaps?

Some tests will have to be done to try and diagnose the source of this issue, which I suspect is an issue with wincache.

**Comment by opengeek** [comment]
opengeek submitted:

As suggested by others regarding similar issues with APC and eAccelerator on LAMP environments, explicitly calling session_write_close() before any code exit point seems to fix the issue with WinCache. I could not reproduce the APC/eAccelerator issue locally, but I believe this will also resolve those issues.

See https://github.com/modxcms/revolution/commit/18e311258a87cd3609a6e6adaa621af5281fe6f8 for commit details.
