### ISSUE TITLE
Container Weblink should present its own URL instead of the target's

### ISSUE THREAD

**Issue by gadamiak** [modxbot/migrate#10586]
gadamiak created Redmine issue ID 10586

A weblink always presents the target's URL. However, when marked to be a container, the weblink should present its own URL, not the target's. The weblink is a redirect and its present behavior as to URL is correct in most scenarios. However, when redirecting to a dynamic target, eg. the newest news article with getResources snippet, the expected behavior would be to present the container's URL. In my example, I have News resource with id=13 , which is a weblink marked as container with alias news and target {{[[~[ &#91;getResources? &parents=`13` &limit=`1` &sortby=`editedon` &showHidden=`1` &tpl=`news.id`&#93; ]]]}}. My resource presents the target's URL news/newest-item.html as its own (link to it in the menu). I would expect it to present its own URL ie. news/ , which should be implied by enabling the container setting. Hope my explanation is clear

**Comment by opengeek** [comment]
opengeek submitted:

I don't agree that the container setting should have anything to do with this, since this already affects internal URL generation (uses container_suffix instead of the Content Type extension). I also believe this should be a request for getResources to add an option to showWebLinkTargets or similar. An option exists on Wayfinder to do this already. That said, I do however believe the core should have an option for doing this when generating links from modWebLink Resource types. I think a system/context setting for link_show_weblink_target could provide a component-generic way to achieve this for future releases, while the getResources specific option can work around your issue for now. What do you think?

**Comment by gadamiak** [comment]
gadamiak submitted:

Giving a second thought on this, I agree that behavior requested should not rely on container setting. The better way is to rely on the alias setting, which would make it consistent with other resource types. modWebLink should use its alias, like other resource types, while it's ignored. Thus in example above, the News weblink should present alias content for the URL or the target's when alias is empty. Combined with the current container setting it will give full control on the URL behavior.

**Comment by opengeek** [comment]
opengeek submitted:

I cannot reproduce the behavior you are speaking of. It seems to always generate the weblink url as the internal url as expected, with the same rules as any other Resource, container or not. If I'm missing something, please clarify for me.

**Comment by gadamiak** [comment]
gadamiak submitted:

Strange, but I can't reproduce it either with latest 2.0.5-dev from git.

Anyway, it's limited to internal URL now so option to use external (target) URL would be useful.

**Comment by opengeek** [comment]
opengeek submitted:

Will add an option for modLinkTags to render the target url for weblinks, along with a System/Context Setting for default behavior.

**Comment by opengeek** [comment]
opengeek submitted:

Added the option "use_weblink_target" to the site area in System Settings. This can be set per Context as well as directly in makeUrl() and via link tag property, e.g.

```
[[~5? &use_weblink_target=`1`]]
```

or

```
$modx->makeUrl(5, '', '', -1, array('use_weblink_target' => true));
```

This also added an $options array parameter to both modX::makeUrl() and modContext::makeUrl().
