### ISSUE TITLE
Add a UUID field to content type tables

### ISSUE THREAD

**Issue by shamblett** [modxbot/migrate#10661]
shamblett created Redmine issue ID 10661

From this forum thread http://modxcms.com/forums/index.php/topic,51114.msg297087.html#msg297087 I believe it would be worthwhile adding a UUID column and an associated revision number to the main content tables, such as site content, snippets etc. I believe this would greatly assist with a number of workflow/versioning/replication scenarios that may need to be implemented in future versions of Revo. I'm not saying the core itself need use this, just that it be available for users if needed.

**Comment by opengeek** [comment]
opengeek submitted:

I'm not convinced this makes anything any simpler; the core of the problem lies in the fact that Resource ID's are referred to in content and/or code. I feel that remapping primary keys via the package installation system is the proper approach for migrating content, and the structure changes that are designed for versioning and making content a primary actor in the design (there will be a content table and class and all content will be managed by this, including Resource and Element content), will take care of a lot of these issues moving forward.
