### ISSUE TITLE
Can't save new Context Access ACL Entry with lower role number

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#10716]
bobray created Redmine issue ID 10716

If there is an existing Context Access ACL entry with a non-zero authority number, I can't create another ACL entry for the same context with a Super User minimum role. The entry doesn't save &#8211; no error message. I can edit the existing entry to give it a Super User role, then recreate the one with the higher number. This happens for both the web and mgr contexts.

**Comment by splittingred** [comment]
splittingred submitted:

Well, technically, that's creating a duplicate ACL, so you shouldn't be able to. Since ACLs with the same target/principals inherit based on authority, best practice would be just to increase/decrease the authority. That said, in r7028, it will now show an error message on the field saying that an ACL already exists for this context.

**Comment by BobRay** [comment]
bobray submitted:

I think you misunderstood the issue, but it's gone now (i.e. works properly). Before, you could create a Context Access ACL with a minimum role or super user, then create another for users with a higher authority #, but you couldn't create them in reverse order.
