### ISSUE TITLE
Clean install fails with Call to a member function execute() on a non-object /core/xpdo/om/mysql/xpdomanager.class.php on line 135.

### ISSUE THREAD

**Issue by gemstone-zz** [modxbot/migrate#10768]
gemstone created Redmine issue ID 10768

Error occurs with a clean install using an existing empty database. This appears to be related to http://modxcms.com/forums/index.php?topic=47476.0 /core/xpdo/om/mysql/xpdomanager.class.php 133 $tableName= $this->xpdo->getTableName($className); 134 $existsStmt = $this->xpdo->prepare("SELECT COUNT(_) FROM {$tableName}"); 135 $exists = $existsStmt->execute(); The statement on line 134 returns a non object due to the fact that the table doesn't exist.
$this->xpdo->errorInfo() returns:
Array ( &#91;0&#93; => 42S02 &#91;1&#93; => 1146 &#91;2&#93; => Table 'modx2.modx2_access_actions' doesn't exist ) Changing to the following allows the install to continue: 133 $tableName= $this->xpdo->getTableName($className); 134 $existsStmt = $this->xpdo->prepare("SELECT COUNT(_) FROM {$tableName}"); 135 if(is_object($existsStmt)){ 136 $exists = $existsStmt->execute(); 137 if ($exists && $existsStmt->fetchAll()) { 138 return true; 139 } 140 } The install appears to complete without further error, but login to manager results in a blank screen.

**Comment by splittingred** [comment]
splittingred submitted:

Does your DB user have access to CREATE TABLE on that database?

**Comment by mtwalsh** [comment]
mtwalsh submitted:

For what it's worth I have just checked out the stable SVN version and hit this error trying to install, it's a show stopper. Checking PHP version: OK! Running: 5.2.10-2ubuntu6.4
Checking MySQL server version: OK! Running: 5.1.37-1ubuntu5.1
Checking MySQL client version: OK! Running: 5.1.37

**Comment by gemstone-zz** [comment]
gemstone submitted:

DB user has full permissions, the issue is that the table doesn't exist at that statement on a clean install.

**Comment by mtwalsh** [comment]
mtwalsh submitted:

I've just tried installing the version from this branch: http://svn.modxcms.com/svn/tattoo/tattoo/branches/2.0 And I hit the same problem, preventing me from completing the installation. So it's the same as on the stable branch too: http://svn.modxcms.com/svn/tattoo/tattoo/branches/revolution

**Comment by opengeek** [comment]
opengeek submitted:

Though I can easily fix the source of the error, as you alluded to Gordon, that does not solve the problem here. In addition, I cannot reproduce this, so I'm struggling to identify the source of the issue. I'm trying to setup a VM with Ubuntu to see if I can reproduce it there, but if anyone has any other details they can share regarding the environment (phpinfo, etc.), please do. You can contact me privately with phpinfo, if need be, but otherwise until I can identify the problem anything might help. BTW: I believe the error is occurring because the PDO driver cannot prepare the statement for some reason, not because the table does not exist, AFAIK.

**Comment by opengeek** [comment]
opengeek submitted:

I've fixed the actual source of the originally reported bug. Let's open a different ticket now for any other issues (i.e. blank manager page after installation appears to complete normally).
