### ISSUE TITLE
Cache Not Cleared when Saving Resources in non-web contexts

### ISSUE THREAD

**Issue by mattcdavis1** [modxbot/migrate#10819]
mattcdavis1 created Redmine issue ID 10819

I have a script that loops through resources from various contexts. On updating a resource in a non-web context, the results do not show up unless I manually clear the cache. Here is the script: <?php $outputArray = array();
$homePageArray = array(); //Get an array of Event Resources
$c = $modx->newQuery('modResource');
$c->innerJoin('modTemplateVarResource', 'TemplateVarResources');
$c->where(array(
'TemplateVarResources.tmplvarid' => 26 //Resource Type TV
,'TemplateVarResources.value' => 'event_page'
));
$c->sortby('unpub_date');
$eventObjects = $modx->getCollection('modResource',$c); //Refine initial array to resources that have "ShowOnHomePage" == Yes
foreach ($eventObjects as $eventObject) {
if($eventObject->getTVValue(9) == 'Yes') { $homePageArray[] = $eventObject; }
} if (count($homePageArray) > 0) { foreach ($homePageArray as $key => $event) {
$event_date = strtotime($event->get('unpub_date'));
$outputArray &#91;&#39;event_date&#39;&#93; = date('l, F jS, Y', $event_date);
$outputArray &#91;&#39;event_link&#39;&#93; = '[ &#91;~&#39; . $event->get(&#39;id&#39;) . &#39;&#93; ]';
$outputArray &#91;&#39;event_campus&#39;&#93; = 'Campus: ' . $event->getTVValue(17);
$outputArray &#91;&#39;event_content&#39;&#93; = $event->get('introtext'); if ($key == key(reset($event))) { echo $modx->parseChunk('EventFirst', $outputArray); if ($key == end(array_keys($homePageArray))) echo '</ul>'; } else if ($key != end(array_keys($homePageArray))) { echo $modx->parseChunk('EventRepeat', $outputArray); } else { echo $modx->parseChunk('EventLast', $outputArray); } }//End foreach ($homePageArray as $key => $event) {}
} //End if (count($homePageArray) > 0) {} else { echo $modx->parseChunk('EventFirst', $outputArray) . '</ul>'; }
?>

**Comment by mattcdavis1** [comment]
mattcdavis1 submitted:

Note: The cache is cleared within its own context. It's just when I'm getting resources from another context that it doesn't work. For example, if I am in context "NC State" (which corrresponds to a subdomain) and I make a change in, say, the introtext field, and then save, the results will immediately show up on the page in that context/subdomain. However, if I run a snippet from the web context that gets the introtext field from the NC State context (among other contexts) via object->get('introtext') and then outputs the data via a chunk, the update will not show up unless the cache is manually cleared.

**Comment by opengeek** [comment]
opengeek submitted:

Having the cache clearing limited to the Context a Resource is in is purposeful; in multi-site situations, clearing the cache for context domain1 should not necessarily clear the cache for domain2. Now, if you have Resources shared in multiple Contexts (via modContextResource), this probably needs to be accounted for; otherwise for now, attach a plugin to the OnClearCache event that clears any additional cache sections you want based on your criteria. FWIW, I'm hoping we can provide advanced cache clearing options for power users in future releases, i.e. you can select specific items or sections of the cache to clear when saving a Resource, Element, or other MODx object that affects your output.
