### ISSUE TITLE
Resource alias not being saved (server-specific)

### ISSUE THREAD

**Issue by opengeek** [modxbot/migrate#10810]
opengeek created Redmine issue ID 10810

See the following threads for initial descriptions of the problem: http://modxcms.com/forums/index.php/topic,47874.0.html
 http://modxcms.com/forums/index.php/topic,47923.0.html This seems to be isolated to specific server environments, but research is going to be required. If you are experiencing this issue, you can assist by providing as much detail as possible about the server environments you have deployed MODx in, as well as the browser( s ) you are using when the problem is encountered.

**Comment by jvdheuvel** [comment]
jvdheuvel submitted:

php info file of jvdheuvel.eu (user jvdheuvel)

**Comment by jvdheuvel** [comment]
jvdheuvel submitted:

It looks like the problem is caused by the server.
On my webserver I can't save the resource alias, on a local appache server the saving does work. I did attach php info file of my server that has the problem. I got the problem with the following browsers:
Firefox 3.6, Opera 10, Safari, Chrome and Internet Explorer 8 I can do research to hopefully solve the problem. The only problem is that I don't know where to start.
When there is a guide, or someone can give me a reference where the database queries are stored and the javascript that is calling them.
It would be a great help.

**Comment by splittingred** [comment]
splittingred submitted:

Try turning magic_quotes_gpc off.

**Comment by jvdheuvel** [comment]
jvdheuvel submitted:

I did put php_flag magic_quotes_gpc Off in the htaccess in the manager and root folder. The settings of the phpinfo from modx are:
magic_quotes_gpc Off On
magic_quotes_runtime Off Off
magic_quotes_sybase Off Off The magic quotes are off, but still I can't save the resource alias

**Comment by mkschell** [comment]
netprophet submitted:

I'm experiencing this issue on Apache Windows PHP 5.3.1 but only on first save of the resource.
Bypassing transliteration solved the problem as suggested here http://modxcms.com/forums/index.php/topic,47874.msg291296.html#msg291296 .

**Comment by maclonghorn** [comment]
maclonghorn submitted:

MySQL: 5.0.41
PHP: 5.2.1
WinXP SP 2
Apache 2.2.4
FF 3.5.3
IE 6x (Save button didn't work)
Safari 5.0

**Comment by maclonghorn** [comment]
maclonghorn submitted:

I removed Zend Server (which I never started) and upgraded both Apache and PHP. Now I have:
PHP: 5.2.10
Apache: 2.2.15 Works now.
