### ISSUE TITLE
Can't save element until category not selected

### ISSUE THREAD

**Issue by ebuster** [modxbot/migrate#10878]
ebuster created Redmine issue ID 10878

All ellemets, except the TV, could not be saved until category not selected.
If you don't have categories, you must select category 'none' any time when you edit elements.
This is bad.
 Category 'none' must be selected automaticaly, or we should not choose it, if we don't want (like TV).

**Comment by splittingred** [comment]
splittingred submitted:

I can't reproduce this at all; I'm easily able to save any Element without problems.

**Comment by ebuster** [comment]
ebuster submitted:

Result In my case.

**Comment by ebuster** [comment]
ebuster submitted:

See last comment.
I don't have categories and never had, may be problem in this?

**Comment by splittingred** [comment]
splittingred submitted:

No, I bet it's because you're using Opera 10.5 Beta2, which is unsupported at this time, since we don't support beta browsers. Opera has also had a long history of being buggy with JS apps. You're also using mysql 5.0.51a, which we have stated is not supported in MODx Revolution, although I dont think that's causing this problem here. The JS !empty check should not fire, since allowBlank is set to true. This seems to be a specific issue with either your browser or your system.

**Comment by ebuster** [comment]
ebuster submitted:

Realy - problem in Opera. Sorry.
