### ISSUE TITLE
User starts on previous users tab in left panel

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#10919]
bobray created Redmine issue ID 10919

If the admin logs off with the Element tree in view and a low-level user logs in and has access to only the Resource tree, the Resource tree appears empty. If the user clicks on the Resource tab, the resources appear. This is true even if the site cache is cleared and permissions and sessions are flushed.

**Comment by splittingred** [comment]
splittingred submitted:

This is due to the browser cookies set by ExtJS to preserve the state...this would only happen if the user was first logged in with an account that could see the element tree, and then a user on the same computer logs in without clearing ExtJS cookies in the same browser on the same pc. I'm going to set this to Won't Fix, because the likelihood of this happening is near 0.01%, and it's a simple user fix - clear any ExtJS cookies.
