### ISSUE TITLE
Quirks in Manager Action log

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#11021]
bobray created Redmine issue ID 11021
1. User filter must be selected twice before it takes effect. 2. No object shown for actions of users other than main admin. 3. No dates shown anywhere.

**Comment by BobRay** [comment]
bobray submitted:

Forgot to mention: 4. Funky display of Calendar image for Date Picker icon.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r6249. User filter now works as expected. Log records prior to the fix earlier (pretty recent) wont have Objects; that was fixed in a prior commit, but isnt retroactive. I cant duplicate your #2 bug - all my users are properly logging errors. #4, the date bug, is already specified in another ticket. Secondly, please specify separate bugs in separate tickets. Thanks.

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed.

**Comment by BobRay** [comment]
bobray submitted:

I noticed a couple more things. 1. User filter doesn't work for limited admin user who can view the log (empty drop-down). 2. Limited admin user can see all Manager actions in addition to his own (may be expected).

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r6252; you'll need to rebuild/upgrade, and make sure your limited access policy has the "view_user" permission.

**Comment by BobRay** [comment]
bobray submitted:

All fixed except date picker icon (duplicated elsewhere).
