### ISSUE TITLE
Install forget to write to /connectors/config.core.php

### ISSUE THREAD

**Issue by spoetnik** [modxbot/migrate#11022]
spoetnik created Redmine issue ID 11022

Check this forum topic:
 http://modxcms.com/forums/index.php/topic,43736.msg260920.html Uploaded the Core folder to: /home/zookah/core/
Uploaded all other files to:/home/zookah/domains/liesdegeus.nl/public_html changing the file /home/zookah/domains/liesdegeus.nl/public_html/setup/includes/config.core.php to point MODX_CORE_PATH to the Core folder outside the webroot The setup spits out good /home/zookah/domains/liesdegeus.nl/public_html/config.core.php and/home/zookah/domains/liesdegeus.nl/public_html/manager/config.core files, but forgets to write the correct MODX_CORE_PATH to /home/zookah/domains/liesdegeus.nl/public_html/connectors/config.core.php

**Comment by opengeek** [comment]
opengeek submitted:

I cannot reproduce this with advanced or svn installs as of revision 6326; this is not possible with traditional installs as it will not try to write the config.core.php files, since with many shared hosting situations the PHP process will not have permission to write to these files. IOW, you cannot use traditional package to deploy MODx with non-standard file locations, or you will need to manually handle the config.core.php files.
