### ISSUE TITLE
Save actionbutton never enables

### ISSUE THREAD

**Issue by martinf55** [modxbot/migrate#1103]
martinf55 created Redmine issue ID 1103

The Save button never enables on resource/element create/update pages, when fields are modified (for me at least). This seems to have happened since rev 5853 of modx.actionbuttons.js. It looks like a timing issue here, from my superficial understanding of the core: /\* if checkDirty, disable until field change */
if (el.xtype == 'button') {
el.listeners &#91;&#39;render&#39;&#93; = {fn:function(btn) {
if (el.checkDirty && btn) { this.checkDirtyBtns.push(btn); }
},scope:this}
} When the 'render' event fires, the el.checkDirty hasn't yet been set, so the checkDirtyBtns array isn't populated?
The previous revision populated this array as the buttons were added rather than at render-time.

**Comment by splittingred** [comment]
splittingred submitted:

I can't duplicate this at all - can you clear your browser cache and refresh the page? This might be due to the ExtJS 3.0 -> 3.0.2 upgrade. That code wont be a problem; el.checkDirty is set in the button config - it's what tells the action buttons to add the button as a dirty-flaggable button. It's more of a config setting than a toggle. That said, I tried this on FF 3.5 and Safari 4, and could not replicate the bug at all.

**Comment by martinf55** [comment]
martinf55 submitted:

Yup it was lack of ExtJS 3.0.2 , I'd forgotten I'd switched in a debug ExtJS 3.0.0 so it didn't get updated from SVN. Thanks for taking a look, sorry for the false report!

**Comment by martinf55** [comment]
martinf55 submitted:

Yup it was lack of ExtJS 3.0.2 , I'd forgotten I'd switched in a debug ExtJS 3.0.0 so it didn't get updated from SVN. Thanks for taking a look, sorry for the false report!
