### ISSUE TITLE
Date picker icon tiling 

### ISSUE THREAD

**Issue by ncrossland** [modxbot/migrate#11040]
ncrossland created Redmine issue ID 11040

In Firefox, the icon within the date picker (e.g. for publish date) don't appear correctly - it appears tiled incorrectly.

**Comment by pulse-xx** [comment]
pulse submitted:

I'll work on this tomorrow. It simply needs a larger sized image. The problem is that the width of the area the icon is covering is currently 29 pixels. However, the gif file is constraining each section to roughly 17 pixels. So we need to expand the gif to 174 pixels wide, and a few adjustments to the css positioning. Easy job, just gotta recreate the date picker image.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r6275
