### ISSUE TITLE
Element category is not assigned to a created property set

### ISSUE THREAD

**Issue by shamblett** [modxbot/migrate#1182]
shamblett created Redmine issue ID 1182

When a property set is created on an element the elements category is not stored with the saved property set, it seems to default to 0. Also, shouldn't we also associate property sets with a namespace as well as/rather than a category? This would allow property sets to be associated with(owned by?) 3PC's like we do with system settings and lexicon entries.

**Comment by splittingred** [comment]
splittingred submitted:
1. Categories arent necessarily grouping items for the Property Sets; not sure we want to connect those in that implicit way. 2. Property Sets to namespaces; no; probably not, since we want to keep Property Sets so they can be shared between components - adding namespace to the relationships would inhibit that. Both of these are great debates for the forum; but we wont be implementing their functionality in the first Revo release. Feel free to create a forum post to discuss.

**Comment by shamblett** [comment]
shamblett submitted:

OK, no probs
