### ISSUE TITLE
Unchecking  Container checkbox  makes children disappear in tree

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1227]
bobray created Redmine issue ID 1227

If you uncheck the container checkbox and save a resource, any children of that resource disappear from the tree. Checking the box and saving brings them back. In Evo, the unchecked box doesn't stick if there are children &#8211; probably the way to go.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed issue in r5713. We're not going to "force" the setting; since we want to allow the flexibility of a Resource with children to still not be a container (to allow for more flexible FURLs). I did, however, change the way the tree renders each node - now its based on children, rather than on leaves.
