### ISSUE TITLE
Show all attached property sets on the Properties tab

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1274]
bobray created Redmine issue ID 1274

Showing the empty default properties grid on the Properties tab when there are property sets attached to an element (but hidden) could make a new user think the attachment process didn't work. If possible, all the attached property set names should show on properties tab at all times. Maybe a set of radio buttons instead of a drop-down list would work. Even better, we could put the default properties and all attached property sets on tabs at the top of the grid.

**Comment by splittingred** [comment]
splittingred submitted:

Uhm, maybe I'm reading you wrong, but the attached Sets do show in the dropdown at the top left of the grid. I don't think radio buttons are a good idea, because of eventual clutter with 7+ Sets on an Element. And the tabs idea; well, good in theory, but in practice, I don't think Ext can do that.

**Comment by BobRay** [comment]
bobray submitted:

The problem is that they don't show until you click on the dropdown arrow. It's potentially consfusing for new users and users who seldom mess with properties. I doubt if most elements will have more than 2 or 3 sets attached, though I could be wrong about that. Most current ones have 0. Tabs would definitely be the way to go. If they're not possible, maybe radio buttons could be a config option.

**Comment by BobRay** [comment]
bobray submitted:

Confirmed fixed.
