### ISSUE TITLE
"Reload Core Entries from Base" and "Clear Cache"  take two tries after Upgrade install

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1420]
bobray created Redmine issue ID 1420

After doing an upgrade install and logging in to the Manager, the first time I run "Reload Core Entries from Base" in Lexicon Management, I get "console running" but nothing else, although the OK button is live. The second time, I get the blue status message about how many strings were reloaded. This only seems to happen after an Upgrade install so it's truly trivial. The same thing happens on the first Clear Cache command after an upgrade, the second one clears a number of files, which could be more serious.

**Comment by splittingred** [comment]
splittingred submitted:

Isn't really an issue; cache is because no files are generated. First issue might be related to AJAX connection, registry message, timestamping, etc. Not sure, but not a big enough issue to worry about, since most users wont immediately be going to clear cache or rebuild lexicons right after an install (only way this could happen).

**Comment by BobRay** [comment]
bobray submitted:

Clear Cache was a little flaky for me for a while. Sometimes I'd get a blank console and would have to run it again. I haven't seen it since the latest upgrade so it may be fixed. I'll file a separate issue if not.
