### ISSUE TITLE
Top Menu structure gets reset upon rebuild/upgrade.

### ISSUE THREAD

**Issue by zaigham** [modxbot/migrate#1657]
zaigham created Redmine issue ID 1657

Top Menu structure gets reset upon rebuild/upgrade.

**Comment by splittingred** [comment]
splittingred submitted:

This is due to a bigger issue; we need a way to specify which columns are updated when a vehicle is installed. In cases like this, too, we might need user input in the setup panel - we're going to want to make sure the default menu structure is persistent for upgrades and new installs; but if a user wants to keep their old setup...this gets pretty darn complex.
