### ISSUE TITLE
Dropdowns display a number instead of the proper setting

### ISSUE THREAD

**Issue by Pont** [modxbot/migrate#1761]
pont created Redmine issue ID 1761

MODx Revolution rev 4746 When editing a new resource in the manager the User Template dropdown displays a number representing the templates place in the dropdown and not the templates name. If you click on the dropdown the proper template names are shown but the number doesn't change until you chose one of the templates (or none) in the dropdown.
The same issue occurs for Content Type under Page Settings.
Saving the resource (Continue Editing selected) doesn't change anything, but saving and closing and after that opening the resource again for editing makes the dropdown display the selected setting properly.

**Comment by splittingred** [comment]
splittingred submitted:

This is an Ext bug. I cannot for the life of me figure out how to fix it. It has to do with the fact that the ComboBox's store isn't yet loaded when setValue is called, since the store doesn't get loaded until the trigger is fired. Ideally, Ext would fire up the store should it not be loaded, and then set the value - however, it's not. Suggestions on fixing this are welcome.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r5752
