### ISSUE TITLE
Freidnly URL suffix is being ignored

### ISSUE THREAD

**Issue by Caomhin** [modxbot/migrate#1782]
caomhin created Redmine issue ID 1782

The Friendly URL suffix appears to be ignored in handling requests. After a bit of testing I discovered that it makes no difference what I set the suffix to, the rewrite will only work with .html appended to the alias. i.e. with a suffix set to .htm I still get a 404 from index.php?q=apple.htm however index.php?q=apple.html works perfectly.

**Comment by Caomhin** [comment]
caomhin submitted:

Actually I think I was looking in the wrong place when I latched onto suffix - this seems to be related to to Content Type setting. I created an XML resource and that will 404 unless I append .xml to the alias I gave regardless of the suffix setting. So basically it looks as if Content Type setting is overriding the Suffix setting.

**Comment by opengeek** [comment]
opengeek submitted:

I tried to find a way to make use of the friendly url prefix and suffix settings, but opted to just let the Content Type define the URL's. I just have not removed them yet because migration utilities for legacy MODx systems can use the information. Also, FYI, any containers that have a Content Type with a mime_type value of text/html will use the container_suffix setting, rather than the Content Type suffix. We'll make this information clearer in the documentation before release.

**Comment by opengeek** [comment]
opengeek submitted:

If someone has ideas for utilizing these values, feel free to reopen with suggestions.
