### ISSUE TITLE
Bug int deleting a group of properties

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1849]
bobray created Redmine issue ID 1849

Deleting groups of properties leads to lots of strange behavior. It seems to work normally for the default properties set, but deleting those deletes properties in the custom sets as well. "Revert All" doesn't get back the ones you deleted in the default set (maybe this is by design but, if so, there should probably be a warning). If you delete a group of props in a custom set, they disappear from the grid, but usually reappear on save.

**Comment by splittingred** [comment]
splittingred submitted:

BobRay, When viewing a property set, it shows the default properties 'underneath' - ie:
1. properties that are from the default are colored gray
2. properties that are in the custom property set and have been overridden in said set are colored green
3. properties that are not in the default and in the custom property set are colored purple So, if you delete a property from the default that is not in the custom property set, then it wont show in the custom set, because it was never there anyway. The UI just shows them to make editing and overriding them much easier. We'll be adding a new manager page for editing property sets directly, and there they wont show the default properties, since property sets can go across multiple elements. As for your bug with deleting a group of properties...I don't get that problem - but are you making sure to save after deleting them?

**Comment by BobRay** [comment]
bobray submitted:

Ok, but the colors don't appear until after they're saved. As for deleting properties, if I select several properties in a custom set, right-click, and select "remove" they disappear from the grid and I'm looking at a shortened property list. When I click on "Save Properties," they come back. The first action implies that properties can be removed from a custom set, which is confusing if they can't be removed.

**Comment by splittingred** [comment]
splittingred submitted:

Gotcha. So the 'remove' item should not show unless you're viewing default properties. Agreed.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r4713

**Comment by BobRay** [comment]
bobray submitted:

Covered by MODX-4713
