### ISSUE TITLE
Package manager install error message when package contains a template

### ISSUE THREAD

**Issue by shamblett** [modxbot/migrate#1884]
shamblett created Redmine issue ID 1884

When installing a package that contains a template, the following error is generated in the console output :- Error 42S22 executing statement: Array ( &#91;0&#93; => 42S22
 &#91;1&#93; => 1054
 &#91;2&#93; => Unknown column 'modTemplate.name' in 'where clause' ) presumably because the site_template table has no 'name' column, only a 'templatename' column. This doesn't seem to affect the installation, which reports siccess and on testing seems to be OK.

**Comment by splittingred** [comment]
splittingred submitted:

This is a problem with your build script - when creating the vehicle, did you make sure to set: XPDO_TRANSPORT_UNIQUE_KEY => 'templatename' for the template vehicle?

**Comment by shamblett** [comment]
shamblett submitted:

Ah! yes of course, I see this now, I'd simply copied 'name' from the chunk attributes.

**Comment by splittingred** [comment]
splittingred submitted:

Yeah, we should have some better documentation on these attributes for beta. We've just been changing them in alpha, so it's been hard to doc until we're done. UNIQUE_KEY basically tells the installer what WHERE parameters to search by to find the object, since it can't search by ID since the ID isn't known yet. UNIQUE_KEY can also be an array of columns, like: array('name','category'), etc. I recommend sticking to the simplest, though, as it is easier.
