### ISSUE TITLE
Can't do upgrade install on existing site in r4316

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#1970]
bobray created Redmine issue ID 1970

Updated to r4316. Did a build (which went fine). I can log in to the Manager and the site looks fine but if I run setup, the only choice is a new install.

**Comment by BobRay** [comment]
bobray submitted:

I just tried an update/build/setup on another MODx site on the same machine and the upgrade went fine. Still no go for the first site, though. The one that won't do the upgrade install is a fresh checkout/build/install from yesterday. It has several working pages in it but is not recognized as installed. What does setup check for the decision on whether it's an already installed site?

**Comment by opengeek** [comment]
opengeek submitted:

I think you are just confused because of the MODX_CONFIG_KEY issue. I am guessing that you modified this value and that setup can't find the config file named based on this value. This is how setup of multiple sites from a single core is possible; this is why the installer needs to prompt users for the core path and config key values before going to the setup options screen. You need to modify setup/includes/config.core.php to match in the meantime.

**Comment by BobRay** [comment]
bobray submitted:

I've never intentionally modified MODX_CONFIG_KEY and I've never run more than one site on a single core. All of my sites are completely separate installs, each with its own core. I wish I could check MODX_CONFIG_KEY to see if there is a mismatch but it's too late, I deleted everything and did another checkout which seems to work fine.

**Comment by splittingred** [comment]
splittingred submitted:

Closing till after alpha-6 release, will test cases then.
