### ISSUE TITLE
Suggested improvements to System Settings screen

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#2164]
bobray created Redmine issue ID 2164

If you want separate issues for all of these, let me know. 1. Correct spelling of Configuration at top of screen (currently "configration"). (appears in system_setting.inc.php (line 13) and english.inc.php (line 1257). 2. Expand "Filter by Key" search to include Setting and value in addition to key. Currently, a search for "database" comes up empty. 3. Add "Setting" at top of "Create New" box. 4. Make xType a drop-down or restrict possible entries in "Create New" box. 5. Change name or xType to something more descriptive (variable type, field type, ??) 6. Add "Help line" (or whatever it's called) field in "Create New" box 7. Make it clearer how to edit a key value. 8. Make Setting and Key editable in addition to value. 9. Organize keys into categories? 10. Gray out or remove plus sign for keys with no help.

**Comment by splittingred** [comment]
splittingred submitted:

Good suggestions - this looks like it's going to take a bit more work, since we'll have to add a column to the tables for timestamping. Filter by setting name is more complex, since those are lexicon strings that are being used, and since those are just array strings, they're not really "filterable" yet. Discussions welcome on alternate lexicon string storage mechanisms. Categories for keys will also need a column, as well. This whole thing could go up for discussion.

**Comment by splittingred** [comment]
splittingred submitted:

Well, this whole thing has got us to create modNamespace, modLexiconEntry, modLexiconFocus, and modLexiconLanguage. More on that soon.
