### ISSUE TITLE
Sanity Check resource and element names

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#2210]
bobray created Redmine issue ID 2210

If we allow resources and elements to be in files rather than the MODx database, their names need to be vetted before saving. Maybe this is already being done but I didn't find it. Using duplicate, I created a snippet named Foo / @#$%.

**Comment by opengeek** [comment]
opengeek submitted:

There will still be db entries and the limitation on these names should be only for the database since it contains the name property. The source content is the only thing that can be stored to file, and the source of that file is indicated in the source field itself (in the database); i.e. it does not have to match the name of the resource/element. This does bring up a good point though in that we should be able to auto-create the files with appropriate names cleansed of any illegal filename characters.

**Comment by BobRay** [comment]
bobray submitted:

The source field doesn't have to match, but the closer it is to the resource name, the easier it will be for the user to find that file if they want to edit or replace it outside of MODx. It might be easier to just use the resource name as the source name and require that it be both DB and filename legal for all file/db systems.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r5124.

**Comment by BobRay** [comment]
bobray submitted:

Fixed (illegal characters are now stripped out).
