### ISSUE TITLE
Locked Elements no longer apply to Revolution principles

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#2265]
bobray created Redmine issue ID 2265

Locking a snippet for editing and saving it makes it disappear from the tree so there's no way to edit or unlock it. The snippet still executes normally.

**Comment by splittingred** [comment]
splittingred submitted:

Mine doesn't disappear from the tree, but does prevent from editing. This seems to be a broader issue - the mgRole session variable is no longer valid in 0.9.7, and there is no Administrator with role ID 1 anymore. May need to change to a SuperUser role, or to any roles with authority 0, or refactor this entirely.

**Comment by splittingred** [comment]
splittingred submitted:

Changing title to properly reflect bigger issue.

**Comment by splittingred** [comment]
splittingred submitted:

A commit removing the checks has been made until a resolution on the issue is made.

**Comment by opengeek** [comment]
opengeek submitted:

What do you think of having a manage_locked_elements policy attribute added to the mgr/connector context policies in order to allow such editing. We then apply default context policies to mgr/connector that give them this permission and modify the controllers/processors to check this permission. The Default Admin user will then be able to access elements "locked" in this manner through the default policy.

**Comment by BobRay** [comment]
bobray submitted:

I'm not sure I understand this completely but it seems that the default amin (the one who does the install) should have all rights to everything by default.

**Comment by mkschell** [comment]
netprophet submitted:

+1 for Jason's idea

**Comment by splittingred** [comment]
splittingred submitted:

I agree with Jason's proposal.

**Comment by BobRay** [comment]
bobray submitted:

Sounds good to me.

**Comment by opengeek** [comment]
opengeek submitted:

This is now controlled by the access policy attribute edit_locked. A user must have this policy attribute in the mgr and connector contexts in order to edit any Element that is marked as locked.
