### ISSUE TITLE
Cannot view/edit module - PHP fatal error

### ISSUE THREAD

**Issue by fmilitao** [modxbot/migrate#2282]
unknown created Redmine issue ID 2282

When creating a new module and hit save, I get the following error but the module saves OK. Fatal error: Class 'modActionButtons' not found in /srv/www/htdocs/modx-097/manager/controllers/element/module/update.php on line 17.
I then cannot get back into the module to view or edit it - the same error appears.

**Comment by splittingred** [comment]
splittingred submitted:

Already fixed in r3666. To fix yourself without using SVN, remove these lines in the offending controller (lines 16-30) // load Action buttons
$buttons = new modActionButtons($modx,array(
'type' => 'update',
'form_id' => 'mutate_module',
'new_params' => 'a=107',
'continue_params' => 'a=108&r=2',
'close_params' => 'a=106&r=2',
'cancel_id' => 106,
'confirm_delete' => $modx->lexicon('confirm_delete_module'),
));
$buttons->add('save');
$buttons->add('duplicate','copy');
$buttons->add('delete');
$buttons->add('cancel');
$modx->smarty->assign('modActionButtons',$buttons);
