### ISSUE TITLE
Published state not updated when state is changed using checkbox

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#2332]
bobray created Redmine issue ID 2332

Changing the publication state with the tab updates the checkbox but the reverse is not true. Changing the checkbox and saving doesn't update the tab so you can have published document with the "publish" tab showing and an unpublished document with the "unpublish" tab showing if you change the checkbox and save the document.

**Comment by splittingred** [comment]
splittingred submitted:

r3608 and beyond handle the top buttons, but not the checkbox. May want to just remove checkbox entirely. What do you think?

**Comment by BobRay** [comment]
bobray submitted:

The checkbox would make an easier transition for 0.9.6 users and new users might not be able to tell if a doc is published or not at first (if they don't know about the indicator in the doc. tree). I don't know how hard it would be to synchronize the checkbox with the top buttons and make the checkbox control the state on change. If it's really difficult, I could live without the checkbox, but I think it adds value. Should the top tabs also be synchronized to reflect changes in the published and unpublished dates? I don't like the idea of an unpublished document with an "unpublish" tab at the top (& vice versa).

**Comment by splittingred** [comment]
splittingred submitted:

Yeah, good points. Are the top buttons causing more problems than they're worth? Are they necessary?

**Comment by mkschell** [comment]
netprophet submitted:

I was just playing around testing this issue and noticed that when you click Publish for example, the document will become published, and if the reload selection is on, the document will reload, still showing any edits you have made to the document. Even though the document has been published, it has not be updated/saved. I understand the logic behind this, but it does lead to potentially confusing difference between server state and client state.
Synchronizing the top button with the checkbox field would be a little tricky because the top buttons are there for immediate action, while the checkbox is part of the document state to be saved when the user is ready.
As you say Shaun, maybe the top Publish/Unpublish button is more problem than it's worth at this point.

**Comment by BobRay** [comment]
bobray submitted:

I agree with Mike, the top buttons don't seem necessary and will cause confusion.

**Comment by splittingred** [comment]
splittingred submitted:

Good enough for me. Nixing them.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r3856.
