### ISSUE TITLE
Duplicate works for Resources and Plugins, but not for Chunks and Snippets

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#2334]
bobray created Redmine issue ID 2334

Trying to duplicate a chunk or snippet generates the error message: chunk not found / snippet not found. Also, Resources and Plugins get a warning/confirmation message before duplication. Snippets & chunks don't (maybe by design).

**Comment by garryn** [comment]
garryn submitted:

One problem is that when trying to duplicate from the 'Edit ...' pages, there is no adequate checking of existing names prior to saving to the database (or a way of entering a new name for the duplicate) - duplicate names then get caught by the UNIQUE indexes on the name fields in the respective tables and the save fails. I think the original problem ('xxx not found' error) is perhaps fixed in rev 3645 by Shaun - but still need to make the name-checking more robust IMO.

**Comment by BobRay** [comment]
bobray submitted:

I think the other "duplicate" functions save the item with the name "duplicate of x" with x being the original name. Then the user can rename the item on edit. There's a small chance that someone would try to duplicate an item twice without doing the name change first and the second dupe operation would fail but it would be a fairly rare occurrence.

**Comment by BobRay** [comment]
bobray submitted:

Original problem is fixed for both snippets and chunks. There's still an issue with duplicate snippet names. I'll create a new item for it. This one should be closed.
