### ISSUE TITLE
Move up closed items in the tree

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#2357]
bobray created Redmine issue ID 2357

Work in the Manager would go significantly faster if the blue closed items bars (Elements and/or Files) appeared just below the open items rather than at the bottom of the screen. When going back and forth between Resources and Elements, it's annoying to have to keep moving the mouse all the way to the bottom of the screen to switch.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r3428

**Comment by BobRay** [comment]
bobray submitted:

The old behavior is back (in 3645). Files and Elements drop to the bottom of the screen when closed.

**Comment by splittingred** [comment]
splittingred submitted:

Unfortunately, what happens when I fix this issue to the other way (the accordion tabs not extending to the whole west panel), a much worse bug occurs - if the tree nodes happen to extend past the panel, then no scroll bar appears, and you cant see the nodes at the bottom. If you use the keyboard to go down, then the toolbar disappears. So, in lieu of that, this won't get fixed, because it causes too many other problems.
