### ISSUE TITLE
Supress unnecessary template change warning

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#2397]
bobray created Redmine issue ID 2397

The warning message that unsaved data will be lost if you change a document's template shouldn't appear if the document was just saved (e.g. not "dirty").

**Comment by opengeek** [comment]
opengeek submitted:

Actually, I believe this message needs to be clarified, but it is necessary, because changing the template changes the relations to template variables bound to the selected template. In fact, I believe this needs to be modified to allow some options: keep orphaned TVs with values customized for the current document OR remove any custom values for orphaned TVs.
