### ISSUE TITLE
Property Sets import action does not save by default

### ISSUE THREAD

**Issue by wshawn** [modxbot/migrate#2506]
wshawn created Redmine issue ID 2506

Imported property sets are not saved and no message is provided stating a save must be completed.

It is stated that the current settings are overwritten, which might imply saved.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in https://github.com/modxcms/revolution/commit/1df92fa910c3574c1f7dc4f1cb7e3c0179262404

I think we don't really want them _saving_ unless the user explicitly tells it to, so I added a check that marks them all as dirty, indicating to the user that the properties need to be saved.
