### ISSUE TITLE
Prevent sendRedirect() from preserving request parameters unless specified

### ISSUE THREAD

**Issue by xpix** [modxbot/migrate#2666]
xpix created Redmine issue ID 2666

Hi

echo "<pre>" . print_r($_SESSION, true) . "</pre>";

outputs the password 

[modx.request.referrer.redirected] => Array
        (
            [login_context] => mgr
            [modahsh] => 
            [returnUrl] => /manager/
            [username] => username
            [password] => _REAL PASSWORD_
            [rememberme] => 1

```
        [PHPSESSID] => 8e35e22ca510560e0c833dsca83b8e6d
    )
```

I'm not sure if other fields need to be removed but someone with better security/revo skills might know better

**Comment by wshawn** [comment]
wshawn submitted:

Jason,

This is also in the $modx object multiple times -- though it is not as insecure as in the $_SESSION, after authentication is completed why is the password needed outside of a change -- which could be handled with ajax.

**Comment by opengeek** [comment]
opengeek submitted:

It is not needed in the SESSION; this was a consequence of a feature added to sendRedirect() that saves the REQUEST parameters for use on the target page. I am working on an alternative approach to allow this feature without polluting the SESSION.

It is required in the config of the xPDO instances because all of the methods which wrap PDO methods provide a connect-on-demand feature.

**Comment by opengeek** [comment]
opengeek submitted:

See https://github.com/modxcms/revolution/commit/a08a0ca4b462c965438a7913ac0180eb0b848929 for commit details on the fix.
