### ISSUE TITLE
Quirks in policy/policy template

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#2730]
bobray created Redmine issue ID 2730

 -- Both Policy template and Template Group show as numbers rather than names. Reloading the page sometimes fixes it, but not always.

 -- Custom policy templates (no matter what group they are in) are not available when creating Resource Group and Element ACL entries; only buit-in policies show.

 -- When creating Context Access ACL entries, all policies except resource-type show. Should probably be limited to Admin types.

 -- I can't replicate this, but I'd swear that some policies have changed to the Admin template group on their own.

**Comment by splittingred** [comment]
splittingred submitted:
1. Fixed in https://github.com/modxcms/revolution/commit/e8a09354d89e009acbb4333d54507c79907746b8
2. Cannot reproduce at all.
3. Disagree; all but Object policy types should be available for ctx Access ACL grids.
4. Fixed via #1.

Can you please file these in separate tickets next time? Makes it difficult to track each item when they're all grouped in one ticket like this.

**Comment by BobRay** [comment]
bobray submitted:

On #3 - the object policies _are_ available -- object; load; and load, list and view are all there for me when adding a ctx access ACL entry.
