### ISSUE TITLE
modext/core directory in different place in Git version of Revo

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#2792]
bobray created Redmine issue ID 2792

The core directory is at:

manager/assets/modext/core/

in the Git version, but in both the traditional and advanced versions it is at:

manager/assets/modext/build/core/

That makes it inconvenient to write code that uses those files that will run in all versions.

**Comment by splittingred** [comment]
splittingred submitted:

No, they're 100% right. The build process compresses the JS and puts it in build, to allow the compress_js setting to use those compressed files in build/ instead of the uncompress, commented code.

If you're writing code that uses MODx JS files, you should be using the core/ ones, not the build/ ones, or (better) you should be using ones depending on what the compress_js setting is.

**Comment by BobRay** [comment]
bobray submitted:

I wanted the file modx-min.js which only exists in the build directory in the git version. Should I have been using modx.js instead?
