### ISSUE TITLE
Extension Packages 2.0.5 traditional

### ISSUE THREAD

**Issue by CyntaxDotDev** [modxbot/migrate#3097]
ReSpawN created Redmine issue ID 3097

The extension packages in MODx Revolution 2.0.5 don't work. As said in the forum, they use the absolute path, which also don't work.

http://modxcms.com/forums/index.php/topic,58348.new.html#new

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in https://github.com/modxcms/revolution/tree/release-2.0.6-pl

Added "serviceName" and "serviceClass" params, which can be used like:

[{"experience":{"path":"[[++core_path]]components/experience/model/","serviceName":"experience","serviceClass":"Experience"}}]

Which would load the "experience" package, and then load the "Experience" class from [[++core_path]]components/experience/model/experience.class.php. serviceClass is the PHP name of the class, where serviceName relates to the filename that it is found in.
