### ISSUE TITLE
Template code (html) layout affects html rendering

### ISSUE THREAD

**Issue by kirkhuyser** [modxbot/migrate#3117]
kirkhuyser created Redmine issue ID 3117

The manner in which HTML is typed in the edit box of a Template affects how the content is displayed in the web page.  For example, typing white space before a line of html code causes the output to be indented in the resulting web page.  And typing list items on separate lines in the Template edit box overrides any CSS settings that create a horizontal list - in other words typing the <li> items vertically in the template edit box creates a vertical list despite the underlying CSS.

It is not uncommon to use indentation when typing HTML code so as to make it easy to follow the structure.  Tables within tables or rows and cells within tables are examples of where indenting helps the developer organize his code.  The white space should not have an affect on how the HTML is displayed in the browser.  Leading white space, however, does not seem to affect table rendering, but it does affect lists and text rendering.

**Comment by splittingred** [comment]
splittingred submitted:

Erm, this is not a problem with MODX - the Template should render the code as you put it into the Template. MODX also does not generate any CSS; so you're probably experiencing an issue with your layout rather than MODX causing the issue.

Closing, as this is not reproducible.
