### ISSUE TITLE
Published checkbox alignment breaks when using Form Customisation

### ISSUE THREAD

**Issue by adamwintle** [modxbot/migrate#3436]
adamwintle created Redmine issue ID 3436

When the Template field is hidden using the Form Customiser the Published checkbox is pushed to the very left edge of the page:

!http://f.cl.ly/items/0R1r102t370C1i1H1J1L/Screen%20shot%202011-01-12%20at%2018.42.12.png!

It would be ideal if the checkbox itself was flush with the other form fields and the label also had a colon (:).

**Comment by Spheerys** [comment]
spheerys submitted:

Same with 2.0.7pl
Not vital, but inesthetic ^^

**Comment by mindeffects** [comment]
mindeffects submitted:

Yes, this is a thing that's bugging me a little (using 2.0.8pl), since I like to hide the template-chooser which then causes the page to look a little "strange" as the screenshot shows very well.

Why not putting "published" just below "Hide from menu:"? And it would be great, if the order was reversed: "Published: [ ]"

<pre>
Hide From Menus: [ ]
Published:       [ ]
</pre>

**Comment by mindeffects** [comment]
mindeffects submitted:

OK, still not a top notch thing but still inesthetic (screenshot above).

Now, after some time, I still would prefer the location next to "Hode From Menus" but with a minor consistence change: negations are somehow confusing. Why not "Show in Menus"?

<pre>
Published:     [X]
Show in Menus: [ ]
</pre>

Sometimes it's the little things that make life easier.

Have a nice 4th of July!
Oliver

**Comment by MarkH** [comment]
markh submitted:

Here's a plugin to get this functionality right now:

http://modx.com/extras/package/movepublished

(Tho it doesn't swap show/hide from menus @Oliver)

**Comment by MarkH** [comment]
markh submitted:

Closing this as it is no longer relevant since the release of 2.2
