### ISSUE TITLE
Upgrade section of script resolver doesn't run on upgrade.

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#3464]
bobray created Redmine issue ID 3464

With this code, the "Install" section of the resolver runs on both install and upgrade for me.

<pre>
<?php
switch($options[xPDOTransport::PACKAGE_ACTION]) {
    case xPDOTransport::ACTION_INSTALL:
        $object->xpdo->log(xPDO::LOG_LEVEL_INFO,'Installing');
        $success =  true;
        break;
    case xPDOTransport::ACTION_UPGRADE:
         $object->xpdo->log(xPDO::LOG_LEVEL_INFO,'Upgrading');
        $success = true;
        break;
    case xPDOTransport::ACTION_UNINSTALL:
        $object->xpdo->log(xPDO::LOG_LEVEL_INFO,'Un-Installing');
       $success = true;
        break;
}
$object->xpdo->log(xPDO::LOG_LEVEL_INFO,'Script resolver actions completed');
return $success;
</pre>

**Comment by BobRay** [comment]
bobray submitted:

Did a little debugging. On Line 34 of processor/workspace/packages/getattribute.php, $options['installed'] is null during an upgrade.

**Comment by opengeek** [comment]
opengeek submitted:

If you reinstall an already installed package version, it will now set the appropriate package_action. However, the package_action on new versions of existing packages is still xPDOTransport::ACTION_INSTALL, since this is based on the installed state of a specific version of the package. Probably needs further discussion and refactoring.
