### ISSUE TITLE
Form Customization Default Values Override Admin-Entered Content

### ISSUE THREAD

**Issue by sepiariver** [modxbot/migrate#4048]
sepiariver created Redmine issue ID 4048

Entering default values for a field overrides Admin-entered values. Manually entered values can be viewed by User Groups not assigned to the Profile, but User Groups affected will only see the default values. This is contradictory to the default values behaviour for TVs, for example. Suggest consistency here.

**Comment by gadamiak** [comment]
gadamiak submitted:

It's by design actually and serves to override any user input in case of resource/update sets. In case of resource/create set it can be used to provide pre-filled default values, which user can change (provided they are not reset again in resource/update).

This is how it should work.
