### ISSUE TITLE
Manager search page (action = 47) ignores permission

### ISSUE THREAD

**Issue by lokamaya** [modxbot/migrate#4074]
lokamaya created Redmine issue ID 4074

Manager search page ignores permission given to specific user.  I guess search page should only displays appropriate resource(s) that match the permission owned by the user.

**Comment by splittingred** [comment]
splittingred submitted:

It does; I cant replicate this:

<pre>
foreach ($resources as $resource) {
    if ($resource->checkPolicy('list')) {
        $resourceArray = $resource->toArray();
        $resourceArray['menu'] = array();
        if ($modx->hasPermission('edit_document')) {
            $resourceArray['menu'][] = array(
                'text' => $modx->lexicon('resource_edit'),
                'params' => array('a' => $actions['resource/update']),
            );
        }
        $list[] = $resourceArray;
    }
}</pre>

**Comment by lokamaya** [comment]
lokamaya submitted:

I look into search connector (Search) and resources tree connector (getNodes). Both are similar, except the search connector only check for resource policy/permission, while getNodes connector check both context and resource policy/permission.

**Comment by lokamaya** [comment]
lokamaya submitted:

I still don't get with "resource->checkPolicy" function and it's option: list, view, edit, delete.

Why this function still allow resource(s) from specific context to be listed, even the user does not have privilege to list/view/access that context.

**Comment by opengeek** [comment]
opengeek submitted:

Zaenal Muttaqin wrote:

> I still don't get with "resource->checkPolicy" function and it's option: list, view, edit, delete.
> 
> Why this function still allow resource(s) from specific context to be listed, even the user does not have privilege to list/view/access that context.

If they can "load" a Context, then they can access Resources in it in general. list/view/save/remove for a Context apply to managing Contexts themselves, not the Resources within them. Resource Groups applied to mgr Context control access to Resources users can access in the manager.

That said, the search could load the Resources by Context in order to properly check the "list" Permission for each Context before presenting the Resources in it. Or, even better might be to add a "search" Permission to the Context policies to check this separately. Thoughts anyone?

**Comment by opengeek** [comment]
opengeek submitted:

Search now requires a user to have permission to 'list' a Context in order to search for Resources within it.
