### ISSUE TITLE
Cannot change template for symlink

### ISSUE THREAD

**Issue by juro** [modxbot/migrate#4369]
juro created Redmine issue ID 4369

When trying to change the template for symlink, upon save it revert back to the original value.
Template can be changed only using Quick update.

**Comment by pavsyk** [comment]
pavsyk submitted:

The same for static resources.

**Comment by mkschell** [comment]
netprophet submitted:

I can confirm the following for rc-3, when changing the Template on a New Symlink or a New Static Resource
- it _does_ trigger the "change template" warning, and it _does_ save the resource, but it _does not_ reload the resource in the Update Symlink or Update Static Resource page
- the Template select list reverts to the previous selection
- because the New xx page does not reload, changing the Template again, or actually Saving creates an additional New *\* Resource

This behavior has changed however in the current release branch. New Symlink and New Static Resource pages _do_ save and reload to Update xx pages.

What could cause confusion, however, is that even though the Resources are getting saved, and re-opened in an Update xx page, with the new Template selected and associated TVs shown, the change in Template hasn't actually been saved _plus the dirty flag for the resource is not set, therefore the Save button is not activated_. This is true of all Resource types. The user must make a change to a field, so that the Save button is actived, then Save the Resource again in order for the Template change to be saved. 

So to make a long story short, my recommendation is to at least have the dirty flag set on an Update Resource page after a Template change.

**Comment by mkschell** [comment]
netprophet submitted:

The following commit ensures that the Save button is active after Template change for all Resource types.
As stated previously, users must still Save a Resource even after the Template change suggests that it is "saving" and reloading the Resource. This is by design and perhaps the messaging around this needs to be more clear.
