### ISSUE TITLE
When alias is blank, and friendly URLs is on, makeURL fails

### ISSUE THREAD

**Issue by ncrossland** [modxbot/migrate#4381]
ncrossland created Redmine issue ID 4381

When 
- an alias field is left blank, 
- its URI is NOT frozen
- friendly_aliases are on

makeURL is not generating a URL. In the past (2.0.8) makeURL would generate a URL based on the document ID. In 2.1RC3 it is generating a blank URL.

e.g.

if resource 72 had a blank alias, in 2.0.8 

<pre>
makeURL(72)
</pre> 

or

<pre>
[[~72]])
</pre>

would generate the URL

/myfolder/72

In 2.1RC3 it is generating nothing.

This means if a user forgets to input an alias, the link breaks. It is much more desirable to have the previous behaviour.

**Comment by ncrossland** [comment]
ncrossland submitted:

Resources without an alias (and without a frozen URI) aren't having a fallback (ID based) URL inserted into aliasMap

**Comment by opengeek** [comment]
opengeek submitted:

Nick, I cannot reproduce this in RC3. I believe this was a bug in RC1, but was already fixed (see #3119 — https://github.com/modxcms/revolution/commit/3d020859f82d31561bfa528a9ed52db190633e32). Saving a Resource with a blank alias creates the proper uri with or without friendly_urls enabled, with or without automatic_alias enabled. Can you provide the precise circumstances which lead to this situation and confirm this is occurring in RC3 (and also that it wasn't a result of upgrading using RC1, since those uri's would have failed while the bug was in place)?

**Comment by ncrossland** [comment]
ncrossland submitted:

Is there a way of forcing all URIs to be regenerated?

**Comment by opengeek** [comment]
opengeek submitted:

Not from the UI, other than changing something like the alias of each top-level parent and saving it—you could then just change them each back after save...

Or here is a script you can run to do this (NOTE you can run from CLI to avoid any access control issues):

https://gist.github.com/917662

I will create a ticket for a feature to be added which would allow administrators to do this from the manager UI.

**Comment by ncrossland** [comment]
ncrossland submitted:

I changed all top level aliases and it seems to have regenerated the aliases correctly - should this be performed automatically as part of the upgrade from 2.0.x to avoid these problems?  

I think the relationshop between alias and URI freeze/specify is quite confusing for the non-technical user now, but that's probably a discussion for elsewhere...

**Comment by opengeek** [comment]
opengeek submitted:

Nick Crossland wrote:

> I changed all top level aliases and it seems to have regenerated the aliases correctly - should this be performed automatically as part of the upgrade from 2.0.x to avoid these problems?  

It does; but if you upgraded to 2.1.0-rc1, the bug was in place and Resources without an alias did not get generated because of the error I referenced. If you upgraded from 2.0.x to 2.1.0-rc2 directly, then it would have generated them properly.

Nick Crossland wrote:

> I think the relationshop between alias and URI freeze/specify is quite confusing for the non-technical user now, but that's probably a discussion for elsewhere...

Probably so...but the addition of a uri field on the Resource enabled some requested functionality and helped solve some critical cache scalability issues, so we'll just need to better document this relationship IMHO.

**Comment by ncrossland** [comment]
ncrossland submitted:

Thanks Jason. Documenting it will be helpful. We have taken to renaming Alias using FC to "Alias (URL) override" on the basis that URLs are generated automatically from the page title, and you only need to complete the alias if you want it to be something different.
