### ISSUE TITLE
Can't update system settings

### ISSUE THREAD

**Issue by adhiarta** [modxbot/migrate#4422]
adhiarta created Redmine issue ID 4422

if change value in system Settings using menu _Update setting_ (floating menu), the value not change

**Comment by mkschell** [comment]
netprophet submitted:

Confirmed, but only in the case of updating a Boolean from false to true.

**Comment by mkschell** [comment]
netprophet submitted:

Related problems in viewing/updating Context Settings.

**Comment by mkschell** [comment]
netprophet submitted:

Boolean system settings weren't updating properly from System, Context or User screens.
Fixed in https://github.com/modxcms/revolution/commit/1f63d96933f6f3e792c76db664b2c3ef239bc013

In further testing I cannot reproduce any other errors related to saving Settings, so I am closing this out.
