### ISSUE TITLE
Resource is immediately saved after having only switched templates

### ISSUE THREAD

**Issue by Martijn1981** [modxbot/migrate#4693]
Martijn1981 created Redmine issue ID 4693

A resource is immediately saved when a user creates a new document, fills in the required fields (like pagetitle) and _changes the template after that_. If the template isn't changed (so when it's left untouched), the document isn't saved. The moment the template is changed: the document is saved.

That shouldn't be happening right? The document should only be saved after clicking "Save" :).

**Comment by splittingred** [comment]
splittingred submitted:

No, in 2.1, the Resource is saved on Template change, since you have to reload the page to change the Template (for TV loading, FC rules, etc).

This is intentional. It is also why it pops up a dialog stating so:

<pre>WARNING: This will save your prior changes to the change and reload the page;
ensure you are ready to do so before proceeding. After the page has reloaded, 
you will need to save again when you are ready to save the Template change.</pre>

**Comment by gadamiak** [comment]
gadamiak submitted:

I recall discussion about this in a ticket concerning FCs and I think it's OK as far as it applies to existing resources, ie. those saved before.

New resources should not be saved on template change, especially those whose template is being switched upon creation as this is the first action when one wants to use non-default template. I recall a mid-step dialog was proposed in which one could specify a template -- which decides about document purpose -- and parent resource -- to satisfy FCs. Passing it would open the current form with those fields filled.

Also having to fill the title to be able to switch template is not, what is expected and, in fact, is confusing as the dialog mentioned doesn't point it out. Also there's no info that template has not been switched due to empty title.

**Comment by Martijn1981** [comment]
Martijn1981 submitted:

That's exactly what I'm thinking! Ah well, perhaps this behavior can be reversed in a future release...
