### ISSUE TITLE
When template is switched before filling in pagetitle, all new resources get the same alias

### ISSUE THREAD

**Issue by Martijn1981** [modxbot/migrate#4863]
Martijn1981 created Redmine issue ID 4863

This is a huge bug. This is how you replicate it:
- create a new resource
- switch template _first_
- the document is saved now with the alias "untitled-resource". I've made this field invisible through FC for webmasters. That's why I couldn't find the source of the bug in the 1st place.
- Fill in a pagetitle and press save: the alias remains the same.

Now repeat the 1st steps above and boom: you'll get errors for all new resources, because all resources will have the same "untitled-resource" alias from now on.

This probably happened because it's now possible to switch templates before filling in a pagetitle. I strongly suggest reversing that move.

**Comment by Martijn1981** [comment]
Martijn1981 submitted:

I'd go even further and say that this is worth a 2.1.0.1 update or something in the very, very nearby future. This is very critical behavior.

Also, this is another disadvantage of saving the resource when switching templates. But I won't go there any further.

**Comment by gerritvanaaken** [comment]
gerritvanaaken submitted:

No, it was exactly the right move! 

Two actions for solving this issue:

1) the alias field of untitled resources should be marked as "temporary", so the first change of the page title does apply a change of the alias, too.

2) Multiple identical aliases should get an ascending number like "untitled-resource-1", "untitled-resource-2", and so on.

It must be possible to change template with an empty resource, because changing templates is always the first thing to do!

**Comment by Martijn1981** [comment]
Martijn1981 submitted:

Definitely not number 2, in all cases, clients shouldn't manually edit their aliases all the time. Should correspond with the latest update of pagetitle. So number 1, yeah.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed for now, in these commits:

https://github.com/modxcms/revolution/commit/1ba6953f144d8eed2220ac57bc1fe3f11351f017
https://github.com/modxcms/revolution/commit/8f0a756f9d3d46ef61972b2afc365b7976e7f93b

This will prevent the alias from being set when the Template is being changed, until a pagetitle is set. If a pagetitle is set, and the Template is changed, then an alias will be built from that. Otherwise, leave blank until a pagetitle is set.

This is a temporary solution until we can figure out a better solution for reloading the create controller with the data saved from the form, which will properly cause the intended actions - rather than loading the update form, as is occurring now. That will probably happen in 2.1.2.

**Comment by Martijn1981** [comment]
Martijn1981 submitted:

Thanks! Good to see it's fixed for now. So am I correct to assume that in the case of having not set a pagetitle (before or after switching template) and attempting to save the resource, the "pagetitle" _will_ be marked as a mandatory field and I won't be able to continue, right?

Just checking to see if it's completely UX proof :p. Thanks in advance!

**Comment by splittingred** [comment]
splittingred submitted:

Yes. The only time it is not mandatory is if you change the template.

**Comment by Martijn1981** [comment]
Martijn1981 submitted:

All I needed to know, thank you.
