### ISSUE TITLE
Nested output filters not parsed properly

### ISSUE THREAD

**Issue by pixelchutes** [modxbot/migrate#4894]
pixelchutes created Redmine issue ID 4894

Upon upgrading from 2.0.8-pl to 2.1.0-pl, I immediately noticed some unwanted output on one my pages: 

<pre>
`]]
</pre> 

In 2.0.8-pl, the following series of MODx tags was being parsed without issue:

<pre> 
[[!$chunk? &param=`[[!snippet:default=`[[!+fi.placeholder:eq=``:then=`1`:else=`[[+fi.placeholder]]`]]`]]`]]
</pre> 

_NOTE:_ This is being ran from a "cacheable" MODx Resource.

In 2.1.0-pl, however, I am now getting the _`]]_ output listed above dumped to the final HTML...? Further, the page is no longer functioning as expected...likely due to some of the new caching changes in 2.1. Perhaps I was going about it incorrectly from the beginning, however I still don't understand why the modx tag snippet is being dumped to the page?

I have cleared the site cache, re-saved the offending resource, etc...nothing seems to help. Is this level of "chaining" no longer supported in 2.1.0+?

**Comment by pixelchutes** [comment]
pixelchutes submitted:

To assist, I should mention that I am using placeholders (e.g. chunk properties) within the master chunk to pull subsequent "dynamic chunks":

_Within my example $chunk above, I have some HTML that also includes:_

<pre>
[[$chunk-child[[!+param:default=`1`]]]]
</pre>

This allows for dynamic chunk inclusion, such as $chunk-child1, $chunk-child2, $chunk-child3, etc... (where initial &param=`1,2,3,[...]`)

**Comment by opengeek** [comment]
opengeek submitted:

This may be related to other nested output filter bugs, but see if the fix for #5152 does anything to resolve this issue for you.

**Comment by pixelchutes** [comment]
pixelchutes submitted:

Good to know, thx Jason. Will most likely wait for 2.1.2-pl to drop to confirm.

**Comment by gadamiak** [comment]
gadamiak submitted:

I observe it in cfb11b0 with @[[+ti.0:eq=`0`:then=`[[+fi.pShipping:eq=``:then=`checked="checked"`]]`:else=``]]@, which returns @checked="checked"`]]@.

**Comment by opengeek** [comment]
opengeek submitted:

I can confirm this is an error with parsing nested output filters, but this ticket duplicates the issues described in #4712.

**Comment by gadamiak** [comment]
gadamiak submitted:

I see another error, which occurs only inside output filters. If output filter value contains a placeholder it fails silently without any record in error log. I haven't tested all filters but the example below shows, what the problem is.

I want to show a notice until user updates the form, and once updated to show the placeholder: @[[+fi.update:ifempty=`Notice to the user`:ifnotempty=`[[+fi.placeholder]]`]]@. This _always_ returns empty unless the placeholder tag is removed. It doesn't matter which output filter contains a tag as it always doesn't work.

Other example: @[[+p1]]@ is undefined yet. @[[+fi.total:eq=`:or:lt=`:then=`sth1`:else=`sth2`]]@ works while @[[+fi.total:eq=``:or:lt=`[[+p1]]`:then=`sth1`:else=`sth2`]]@ doesn't.
