### ISSUE TITLE
Can't edit admin profile at DB cache-on.

### ISSUE THREAD

**Issue by sama55** [modxbot/migrate#5366]
sama55 created Redmine issue ID 5366

When DB cache is enabled, user's profile is not changed.

Operation:
1. system > settings > cache DB > ON
2. user > profile > general > Edit full name etc. > save

Is this specification?

**Comment by opengeek** [comment]
opengeek submitted:

It is actually updating the database but is not retrieving/showing the new user data until the cache is refreshed manually and the page reloaded.

**Comment by Jsewill** [comment]
jsewill submitted:

We're seeing this problem through MODx 2.1.3-pl.  Not only is the admin profile editor effected, but also the gallery extra and our custom extras (CMPs).  Using rackspace cloudsites, so DB is external to the server where the modx installation resides.  Any idea how I could apply a temporary fix prior to this being corrected in a release?

**Comment by gerritvanaaken** [comment]
gerritvanaaken submitted:

Please turn this bug into "critical". 

With "cache_db" on, the whole manager is nearly unusable, because changes in data tables won’t get displayed! Plus you cannot save newly created resources! (see my recent bug reports)

If it can’t be fixed right now, there should be a big warning text, so nobody ever activates "cache_db". It’s toxic and ruined several hours of my recent working days.

**Comment by opengeek** [comment]
opengeek submitted:

Fixed for 2.2.0-rc1 — see https://github.com/modxcms/revolution/commit/aefac5a400b92095391e3f97067910878e603238
