### ISSUE TITLE
isProcessingTag bug preventing placeholder filtering

### ISSUE THREAD

**Issue by jrotering** [modxbot/migrate#5377]
jrotering created Redmine issue ID 5377

My templates use code like this:

  [[+bodyContent:default=`[[*content]]`]]

Some of them have a 'bodyContent' property that specifies a chunk with a div structure (which has the [[*content]] chunk somewhere within it).

But for the ones that don't have a 'bodyContent' property, the code above is just supposed to revert to [[*content]].

This was working in 2.0.8, but is not working in 2.1.3.  

Posted in forums, and it was confirmed as a bug by Jason.

**Comment by opengeek** [comment]
opengeek submitted:

This is a bug with the new modParser->isProcessingTag() getting set to false and preventing proper output filtering when non-cacheable tags are being processed. That said, using a filter like this is not very efficient because the parser is going to process the placeholder's nested tag, i.e.

  [[*content]]

and discard the output during the cacheable parsing of the Resource multiple times. When the non-cacheable phase is reached (and this bug is not present), the content is parsed again and finally returned by the default output filter. This is a result of the special needs of placeholders during parsing, i.e. they can't be evaluated against conditional expressions until the final non-cacheable phase of parsing.

Even when this bug is fixed, it would be much better to always have a bodyContent placeholder set (via Template property or otherwise) before the placeholder tag is parsed, or to mark the content tag non-cacheable, i.e. 

  [[!*content]]

so it is not evaluated at all until the final phase.

**Comment by opengeek** [comment]
opengeek submitted:

This is fixed for 2.2 and will be ported back for the next 2.1 patch release. See the following commits for details:

https://github.com/modxcms/revolution/compare/b1d799195b...82b065656b
