### ISSUE TITLE
Template Variable returns value "true" after the content is saved and reloaded

### ISSUE THREAD

**Issue by KristianP** [modxbot/migrate#6073]
KristianP created Redmine issue ID 6073

When editing the TV of a resource the content is correctly stored to the DB but after I reload the page the TV contains the value "true".

I expirenced this problem after i did a test upgrade of my current Project 2.1.5-pl to 2.2.0-rc1.

h1. TV Configutration 1:

h2. Input Options

Input Type: Text
Input Option Values:
Default Value:
Allow Blank: Yes
Max Length:
Min Length:

h2. Output Options

Output Type: text

h1. TV Configutration 2:

h2. Input Options

Input type: image
Input Option Values:
Default Value:

h2. Output Options

Output Type: text

**Comment by Seel-Media** [comment]
seel-media submitted:

currently experiencing the same issue.

But it's not "true", it's the value of the first TV of the ressource (in your case "Sideshow Sidebar" - this "Anzeigen" means "true"...right?)

In my case the first TV is a textfield with the content "[[+pagetitle]]" and every other TV of this ressource gets the same content after reloading.

**Comment by KristianP** [comment]
KristianP submitted:

Ok now it's getting weird...

as you can see on the picture i've multiple tv's on one page.

The first TV od the category "Slideshow" has the following configuration:

Input Type: Radio Options
Input Option Values: Anzeigen==true||Verstecken==true
Default Value: true
Allow Blank: false
Columns: 1
Output Type: Text

The second TV config:

Input Type: Text
Input Option Values:
Default Value:
Allow Blank: Yes
Max Length:
Min Length:
Output Type: text

And the third:

Input type: image
Input Option Values:
Default Value:
Output Type: text

If the first TV is set to "_false_" ("Verstecken") then i can save and modify my tvs as i want and the returned value is correct.

If I set the first TV to "_true_" ("Anzeigen") and the sencond TV has any value, the second and third TV will return "true" after I save the resource and reload it.

If the first TV is set to "_true_" and the second TV has _no_ value but the third TV has any value the content is saved correctly and after reload the values display correct.

It seems that the value of the first TV gets populated on the other TV's.

@Christian Seel yes you are right the value is "true". If i change it to "1" the fields will display "1".

**Comment by splittingred** [comment]
splittingred submitted:

I can't seem to reproduce this in any form. Can one of you detail an _exact_ usage case and all the steps you took to get this to occur?

**Comment by pixelchutes** [comment]
pixelchutes submitted:

If it helps, in my setup I have multiple TVs in 3 or more separate categories... approx. 10 TVs of varying types (RichText, GalleryItemTV, Select, Checkbox, Number, etc) -- most of them with some kind of DEFAULT VALUE, and a few using @INHERIT bindings -- I'm not sure if it's related to the TV setup specifically or not. What was involved in your tests?

On #6083, I posted this screenshot: http://bugs.modx.com/attachments/413/duplicate_tv_value-1.jpg ilustrating the behavior.

I have been using Nov 15th nightly exclusively, since I believe this bug was introduced on or around Nov 16th -- _I'm not sure if any recent commits have resolved this issue_, but perhaps you can try your same tests on the initial RC-1 download or Nov 16th nightly, then compare against latest "develop" to see if that changes anything for you? Unfortunately I cannot test the latest nightly on my current instance, atm.

**Comment by pixelchutes** [comment]
pixelchutes submitted:

UPDATE: I decided to risk it and made the switch (upgraded to 12/7 nightly) -- As far as I can tell, this issue has gone away :)

**Comment by splittingred** [comment]
splittingred submitted:

Hooray, good deal. I can't replicate it for the life of me. :)
