### ISSUE TITLE
220-rc2 manager (still) won't load

### ISSUE THREAD

**Issue by goldsky** [modxbot/migrate#6383]
goldsky created Redmine issue ID 6383

related with the previous bug (http://bugs.modx.com/issues/6063)

**Comment by opengeek** [comment]
opengeek submitted:

The previous issue was resolved, and in addition, you no longer have to set the manager_js_document_root for min to work; it should automatically handle any virtual directory paths with things within the manager (or the document root).

In order to provide additional assistance, we will need details on your environment and specifically what the symptoms are.

**Comment by goldsky** [comment]
goldsky submitted:

Revolution 2.2.0-rc2, traditional distro.
Tested on Firefox 8.0, Chrome 16.0.912.63 m, Opera 11.52, and Safari 5.1.2.
All the same.

no error_log, but here are the install logs, from D:\localhost\test-modx-2.2.0-rc2\core\cache

**Comment by opengeek** [comment]
opengeek submitted:

I need the PHP errors, which may be logged in the Apache error_log, or if you can use your browsers developer tools to see why the requests are failing to min. Are you getting Bad Request responses or 500 Server errors from the calls to min?

Also, what is your $_SERVER['DOCUMENT_ROOT'] and how are you accessing your site? URLs, and physical paths if different from the document root.

**Comment by goldsky** [comment]
goldsky submitted:

Alright, I almost there.

I found the culprit from my side.
The templates call requests without stated _min/index.php_ explicitly.
They only determine _min/?f=_, or  _min/?g=_.
That's why the CSS and JS won't be loaded.

I've make some changes to those templates, and seems they're starting to work.
I still can not find some other template files, that might be hidden in a dynamic call.
Please see this attachment.

**Comment by goldsky** [comment]
goldsky submitted:

YES! Got them all!

The curse belongs to _modmanagercontroller.class.php_
Just search and replace these:

<pre>
// src="'.$minDir.'?f='
src="'.$minDir.'index.php?f='
</pre>

or

<pre>
// 'min/?f='
'min/index.php?f='
</pre>

see attachment.

**Comment by MarkH** [comment]
markh submitted:

There's a ht.access in that min dir - when you revert your class, and change that ht.access to .htaccess, does that solve the issue as well?

I think it would be interesting to see what the contents of the combined and minified files are - in your almost-there file it shows a doctype meaning it's returning HTML - possibly some PHP errors that need to be resolved?

**Comment by goldsky** [comment]
goldsky submitted:

Just avoid .htaccess hack.
The script should independent from redirect, except FURL.
That only applies to Apache server, not to IIS.

The doctype didn't mean anything.
The real log was the complete HTML on that page.
There is no PHP error whatsoever, in apache's error log, or in modx's.

**Comment by opengeek** [comment]
opengeek submitted:

This is actually a server configuration error. Most web servers that handle PHP files will have index.php load from any directory requests, like /min/. I will make these changes, but index.php should be configured to load in directories within MODX for proper operation; otherwise, requests to the root of your site might not be handled properly either.

**Comment by goldsky** [comment]
goldsky submitted:

I'm not sure that this is a MODx's coding standard.
I even believe that http://bugs.modx.com/issues/6381 also came from the same cause.

I had a problem with TinyMCE's processors also because of this habit.

I just hope that this is not become MODx's 'validated' standard.
