### ISSUE TITLE
External development and CMP data acquisition

### ISSUE THREAD

**Issue by ghost** [modxbot/migrate#6572]
sottwell created Redmine issue ID 6572

Working with the Doodles tutorial and with modExtra under external development fails when the CMP should be displaying data in the data grid. The snippet displays the data in the table as expected, and the panel and grid are generated correctly, but the grid never gets beyond "No data to display". This appears to be a namespace resolution difference in 2.2 so the processor is not returning the database query results as expected.

Installing Doodles as a component from the Package Manager works fine. It's only when trying to run it externally that it fails. 

All Revo configuration settings have been created or modified as per the tutorial, including the cookie path setting.

**Comment by splittingred** [comment]
splittingred submitted:

This is because you haven't created the DB tables yet, which are done in the resolver during the installation of the package. You can't just plop the PHP code in there and expect it work. :P

Secondly, this is not an issue in Revo - this is better under the Doodles issue tracker, or elsewhere. Closing.
