### ISSUE TITLE
Can't change template

### ISSUE THREAD

**Issue by kevince52** [modxbot/migrate#6589]
kevince52 created Redmine issue ID 6589

Cannot change template. Selecting the new template results in normal working message. "Are you sure you want to change the Template?" Click on yes, saving dialog appears, new template name appears temporarily in drop menu. Page reloads with URL:

<pre>
.../manager/?a=30&id=28&reload=4f06fafc7b6d45.12606643 (this number changes)
</pre>

Resource reverts back to old template.

**Comment by kevince52** [comment]
kevince52 submitted:

Sorry. My bad. Issue is related to PHP timezone problem. Not a bug.

**Comment by siteleas** [comment]
siteleas submitted:

I do not know how to resolve this problem. The statement was made that it was a timezone issue, but there was no resolution steps posted. I experience the same problem with the template reverting back to the previous template after save. How do I resolve this issue? Be sure to put the steps in, so that all others can resolve the problem as well. By the way, I never had this problem with Revo 2.1.5-pl, so this is a new development and what I would certainly call a bug.

**Comment by siteleas** [comment]
siteleas submitted:

By the way, using batcher to update the template for a page works just fine. (this could be a work around for others experiencing the problem until a detailed answer is posted).

**Comment by bchalker** [comment]
bchalker submitted:

Possible fix posted here. http://forums.modx.com/thread/73555/can-t-change-template-in-revo-2-2-solved
