### ISSUE TITLE
Form customization not working on second create-based rule set

### ISSUE THREAD

**Issue by IsaacN** [modxbot/migrate#6906]
isaacn created Redmine issue ID 6906

I'm running into an issue where only the first form customization rules with an action of resource/create and a parent constraint works. All resource/update actions seem to work, and if you disable the first create rule, the second create rule begins working. Symptoms are the same as this issue: 

http://bugs.modx.com/issues/2819

**Comment by splittingred** [comment]
splittingred submitted:

Can you be very specific, detailing exactly what the rules are and what they change?

**Comment by IsaacN** [comment]
isaacn submitted:

_First ruleset, rule 1:_
Action: Create Resource
Template: <template to act on, in this case, "Floorplan">
Constraint Field: parent
Constraint: <id of parent, in this case 5> 

_First ruleset, rule 2:_
Action: Update Resource
Template: <template to act on, in this case, "Floorplan">
Constraint Field: parent
Constraint: <id of parent, in this case 5> 

_Second ruleset, rule 1:_
Action: Create Resource
Template: <template to act on, in this case, "Unit">
Constraint Field: parent
Constraint: <id of parent, in this case 23> 

_Second ruleset, rule 2:_
Action: Create Resource
Template: <template to act on, in this case, "Unit">
Constraint Field: parent
Constraint: <id of parent, in this case 23> 

Both rules set a default template, move some fields around, and hide some fields. For the first ruleset, Rules 1 and 2 work great. For the second ruleset, only rule 2 works. Any more detail you want?

**Comment by splittingred** [comment]
splittingred submitted:

Are these rule set's setting the same default template that they are constrained by?

**Comment by IsaacN** [comment]
isaacn submitted:

Yes. At first, I thought that might be the problem, but it doesn't seem to be the case since the first ruleset works and the second doesn't.

**Comment by splittingred** [comment]
splittingred submitted:

Right, but that may be happening because the template of that parent resource for the first rule is set to the template you're constrained by. The 2nd might not be the same case.

In any way, you cannot "constrain" a rule to a template you haven't yet set as the value - MODX checks the constraint _first_, and if the constraint doesn't match, then it's not going to load the rule. You'll need to force the default template in one set (with the same parent ID, but no template constraint), and then do all your template-specific mods after that in the separate set that has the template constraint.

**Comment by IsaacN** [comment]
isaacn submitted:

"Right, but that may be happening because the template of that parent resource for the first rule is set to the template you're constrained by. The 2nd might not be the same case."

Nope -- both parents are using the template "Page". 

"In any way, you cannot "constrain" a rule to a template you haven't yet set as the value - MODX checks the constraint first, and if the constraint doesn't match, then it's not going to load the rule. You'll need to force the default template in one set (with the same parent ID, but no template constraint), and then do all your template-specific mods after that in the separate set that has the template constraint."

So what you're saying I should do is create 3 rulesets:

_Ruleset 1, rule 1:_
Action: Create Resource
Template: Page
Constraint Field: parent
Constraint: 5

_Ruleset 1, rule 2:_
Action: Create Resource
Template: Page
Constraint Field: parent
Constraint: 23

and _then_ do my other two rulesets from above?

Any idea why it works for the first ruleset above, when apparently it shouldn't?

**Comment by IsaacN** [comment]
isaacn submitted:

I just tested this as above, and it doesn't really work. The template is set on the form correctly, but the reload that brings in the correct template variables never happens. 

Basically, I need to be able to set a template based on the parents and have the TVs come in properly on create. This happens with one ruleset but does not happen with an identical second ruleset (identical except for the template id and parent constraint).

One way or another, it's a bug -- either it shouldn't happen in the first ruleset or it should in the second; I'd argue that having it work in the second ruleset is the way it _should_ be, so that the end user doesn't have to interact with the template field on every instance of a child in the example of a podcast, blog post, news item, etc.

**Comment by dafyk** [comment]
dafyk submitted:

I would like to re-open this bug because its still present in 2.2.6. If i create 2 TVs and then create 2 form customization sets (targeted with constraints to parent=1 and parent=2), then "set show both TVs in parent1" and "set hide both TVs in parent2" I expect to see both TVs when editing resource under parent1 and when editing resource under parent2 i expect no TVs, but currently in 2.2.6 only "disabled" rules are effective meaning i dont see TVs under parent1 (expect to see both)
