### ISSUE TITLE
lexicon->load ignores the given language

### ISSUE THREAD

**Issue by wanze** [modxbot/migrate#7200]
Wanze created Redmine issue ID 7200

When loading a lexicon topic we can set the language in the load method like this:

@$modx->lexicon->load("language:namespace:topic");@

This didn't work for me. It seems that the cultureKey must have the same value as the language,
otherwise modx returns only the lexicon-keys.

Example:

@//Not working
$modx->lexicon->load("de:mynamespace:default");
$modx->lexicon->("mykey"); //Returns mykey, not the value!
//This works
$modx->setOption("cultureKey","de");
$modx->lexicon->load("mynamespace:default");
$modx->lexicon->("mykey"); //Returns correct value for mykey in german@

**Comment by splittingred** [comment]
splittingred submitted:

That's because you're using the $modx->lexicon() method improperly. :)

The lexicon() method will always return the current cultureKey unless you override it manually. While load() allows you to load a different language than the cultureKey, it does not set the cultureKey (purposely) and therefore will not affect how lexicon() works.

To call a lexicon string in a different language, after loading it, you would do something like this:

<pre>
// assuming cultureKey is set to 'en'
$modx->lexicon->load('de:mynamespace:default');
$stringInGerman = $modx->lexicon('mykey',array(),'de');
$stringInEnglish = $modx->lexicon('mykey');
</pre>

**Comment by BobRay** [comment]
bobray submitted:

Is there anything wrong with putting this above the lexicon->load() ?

<pre>
  $modx->setOption('cultureKey', $language);
</pre>
