### ISSUE TITLE
Media source label for files tree in files tab displays 'files' instead of MS name

### ISSUE THREAD

**Issue by gadamiak** [modxbot/migrate#7447]
gadamiak created Redmine issue ID 7447

As in subject. I reported an issue for this some time ago, which was resolved, but what has left is the behavior on first displaying of the files tab. When switching to files tab a default media source is selected (as set in system settings) and its files tree is displayed. However, the root node for the tree has label of 'files' and not the MS name. Once another (or the same) MS is selected, the label is displayed correctly, ie. it shows the MS name.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed: https://github.com/modxcms/revolution/commit/46b1e6a83ee863b4d6d6728aa6b243f61d512d34

Changed the default text to "Media" to prevent confusion. However, this can't be the name of the media source, since that would require an extra AJAX query to get the name of the source - something i'd like to limit.
