### ISSUE TITLE
Missing Language Topics when adding new Action

### ISSUE THREAD

**Issue by jgulledge19** [modxbot/migrate#7578]
jgulledge19 created Redmine issue ID 7578

I have 2.2.1 on my test box and I am creating a new CMP and the Language Topic field is not an option anymore.  And when I loaded up my CMP the lexicons where not loading.  I added the option manually to the DB table and resaved the action and then it worked.

Thanks for reviewing.

**Comment by splittingred** [comment]
splittingred submitted:

That's because they're deprecated. :)

See: http://rtfm.modx.com/display/revolution20/Developing+an+Extra+in+MODX+Revolution%2C+Part+II

Note how manager controllers are now class-based; they will still "work" in the old format, but the loadheaders, lang_topics, etc fields will not. You need to use the class format (see that tutorial, or any core manager controller), and set the language in the getLanguageTopics class method, like so:

<pre>
    public function getLanguageTopics() {
        return array('doodles:default');
    }
</pre>

**Comment by jgulledge19** [comment]
jgulledge19 submitted:

Thanks for the quick response, I will review that page.  You may also want to update this page in the docs: http://rtfm.modx.com/display/revolution20/Custom+Manager+Pages to note this change for 2.2.*.
