### ISSUE TITLE
Using custom rewrite rules for FURLs not working since 2.2.1

### ISSUE THREAD

**Issue by papachumba** [modxbot/migrate#7933]
papachumba created Redmine issue ID 7933

As per
http://forums.modx.com/thread/76631/2-2-2-and-weird-rewrite-behaviour

We need a setting which will ensure custom rewrites still work from 2.2.1 onwards, when using custom FURLS using subfolder structure which are rewriten to modx pages.

This applies when trying to do the following:
_friendly url required:_
/123/456/789/name.html
_modx furl page:_
/something.html?a=123&b=456&c=789&d=name

rule in place:
@#custom rewrite
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^([^/]+)/([^/]+)/([^/]+)/([^/]+).html /something.html?a=$1&b=$2&c=$3&d=$4 [NC,L]
# The Friendly URLs part

RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ index.php?q=$1 [L,QSA]@

the above works fine up to 2.2.0, but not anything after...

**Comment by opengeek** [comment]
opengeek submitted:

Added a new System Setting for 2.2.3, friendly_urls_strict, which is disabled by default, and will again allow custom rewrite rules to any Resources. When enabled, the expected behavior is to 301 redirect any custom rewrites (or any other non-canonical requests that match a Resource) which do not match (at least) the beginning of the original REQUEST_URI. This must be enabled manually.

See https://github.com/modxcms/revolution/commit/aed4dca4ff881561916a27c390787a0728171761 for commit details.
