### ISSUE TITLE
Template Variables missing on Revo 2.2.2

### ISSUE THREAD

**Issue by infomax** [modxbot/migrate#8104]
infomax created Redmine issue ID 8104

After upgrade to version 2.2.2 from 2.2.1, my Template Variables do not show up when I edit a resource.
Clear cache (MODx, Browser) don't solve the problem. I downgraded to version 2.2.1 and everything works correct.

**Comment by maxpiepenbrink** [comment]
mido submitted:

Hi Max,
I have the same problem after upgrading from 2.2.1 to 2.2.4
Could you fix it?

**Comment by opengeek** [comment]
opengeek submitted:

Can you please provide detailed information about the Template Variables that are not showing up after upgrade? Without additional information, there is no way for me to reproduce this issue.

**Comment by maxpiepenbrink** [comment]
mido submitted:

Hi,
After upgrading to MODX 2.2.4 Template Variables are missing.
This error has been reported in forums from many users with no FCs rules or access permission policies.
It has been tested with support team also and they checked there is nothing wrong in configuration.
Evereything was working fine before the upgrade, but not after.
There are a lot of details in this threads:
http://forums.modx.com/thread?thread=77576#dis-post-436467
http://forums.modx.com/thread?thread=78050#dis-post-431449

My enviroment:
Upgraded from MODX 2.2.1 to 2.2.4
Linux
PHP 5.2

There are many users reporting this bug in forums and I have some customers waiting to have their websites deployed because of this bug.
If you want you can contact me ( info@netfactory.es ) or Skype midomidito. I can give you access to the manager to check it.

**Comment by maxpiepenbrink** [comment]
mido submitted:

If you need more information or a test enviroment to reproduce the problem, please, contact me.
Mike, from support, took a look to configuration, we have talked about this in forums, but the problem persists and is causing me ( and other users ) so many problems.
I hope this can be solved for next upgrade.

**Comment by maxpiepenbrink** [comment]
mido submitted:

I attach an screenshot. You have more information in forums

**Comment by maxpiepenbrink** [comment]
mido submitted:

There is a lot of new information regarding this problem in forums:
http://forums.modx.com/thread/?thread=77576
Please, try to fix it as soon as possible because this is causing me a lot of problems , and there are some other users having problems too.

**Comment by maxpiepenbrink** [comment]
mido submitted:

Upgraded to modx-2.2.5-dev-20120920.zip but the problem persists.

**Comment by opengeek** [comment]
opengeek submitted:

There are a variety of possible issues in that thread, from Chrome (or other browsers) being stubborn with cached javascript, to specific Extras which install custom Template Variables that could be responsible for this behavior. I'm closing this as not reproducible. If someone has evidence to the contrary, which does not involve a specific Extra's Custom Template Variable or browser caching issues, please reopen and provide that additional info.
