### ISSUE TITLE
Cache is not updated after new resource

### ISSUE THREAD

**Issue by yama** [modxbot/migrate#8414]
yama created Redmine issue ID 8414

https://github.com/modxcms/revolution/blob/develop/core/model/modx/processors/resource/create.class.php#L608
Cache is not updated after new resource

**Comment by yama** [comment]
yama submitted:

Not working preview button after the saving new resource.

**Comment by yama** [comment]
yama submitted:

//OnDocFormSave
if($mode==='new') $modx->cacheManager->refresh();

**Comment by RTOSkit** [comment]
RTOSkit submitted:

ya ma wrote:

> https://github.com/modxcms/revolution/blob/develop/core/model/modx/processors/resource/create.class.php#L608
> Cache is not updated after new resource

Hello,
I've been carefully inspected your problem
and I have ascertained that when correctly selected the control flag "Empty Cache"  the program responds perfectly and I do not get regenerate their error.

I've added two screenshot so you could see how the program evaluates correctly, the condition to execute or not execute the  "Empty cache"

Regards

**Comment by RTOSkit** [comment]
RTOSkit submitted:

ya ma wrote:

> Not working preview button after the saving new resource.

Hello,

For this problem, 
I think you should open another "issue" because it has no relation with the parent thread.

Regards.

**Comment by RTOSkit** [comment]
RTOSkit submitted:

ya ma wrote:

> Not working preview button after the saving new resource.

Hello,
I will answer directly here,

In the system without "FURL" enabled, the preview works correctly in all cases.

But actually on a system with FURL enabled, the system say "resource updade" discriminates the newly created resources.
As can be seen in this piece of source code:

https://github.com/modxcms/revolution/blob/develop/core/model/modx/modcontext.class.php#L233;#L248

And so the variable "previewUrl" is null, so you can not see the preview in the first save of the resource, while the second time you save resource, can see the preview, because the new array "aliasmap" will contain the new alias .

I've done a small arrangements needed to that preview system  work properly, I will do a pull by the official repository of "revolution", and if the big bosses of MODx accept the code will be available in the next "pl".

https://github.com/modxcms/revolution/pull/351

Regards

**Comment by yama** [comment]
yama submitted:

Very thanks, Maurizio.

I have a different way of thinking.

https://github.com/modxcms/revolution/blob/develop/core/model/modx/processors/resource/create.class.php#L189
I am try print_r($scriptProperties) on this point.
Return value is "syncsite=0".
0?
Actually, this is 1.

**Comment by yama** [comment]
yama submitted:

I became clear.
This issue is very easy, and this is not bug.

!http://kura2.photozou.jp/pub/550/280550/photo/149527817.v1345277836.png!

Look the create new resource screen.

**Comment by yama** [comment]
yama submitted:

https://github.com/modxcms/revolution/commit/b82eea23dac17c120600e1da32be0cd835fb6e59

Fixed this issue.

**Comment by RTOSkit** [comment]
RTOSkit submitted:

ya ma wrote:

> Very thanks, Maurizio.
> 
> I have a different way of thinking.
> 
> https://github.com/modxcms/revolution/blob/develop/core/model/modx/processors/resource/create.class.php#L189
> I am try print_r($scriptProperties) on this point.
> Return value is "syncsite=0".
> 0?
> Actually, this is 1.

The important thing is to fix the problem, not who solves it,
and I'm glad you found the solution and make a fix issue

And you hopefully will have given you my other help in the topic of the resource preview

Regards
