### ISSUE TITLE
Add compound index on modTemplateVarResource

### ISSUE THREAD

**Issue by andchir** [modxbot/migrate#8489]
andchir created Redmine issue ID 8489

800 resources

without tvFilters
php time 1,6226 s

&tvFilters=`param===value`
php time 8,6630 s

Remove of the sub-queries when tvFilters. Replace by individual queries.

**Comment by TriAnMan** [comment]
trianman submitted:

This issue is actual only for MySQL prior to 5.1. I've tested on 5.0.96, 5.1.66 and 5.5.29.

For fix it you have to update MySQL scheme this way:

<pre code class="sql">
ALTER TABLE `modx_site_tmplvar_contentvalues` 
    ADD INDEX `tv_cnt` (`tmplvarid` ASC, `contentid` ASC);
</pre>

Also this index makes such queries about 30% faster on MySQL 5.1.66 and 5.5.29

I wish this fix will be included in further versions of modx.

**Comment by TriAnMan** [comment]
trianman submitted:

Using &depth=`0` when applicable in getResources also speedups page generation about 50%

**Comment by TriAnMan** [comment]
trianman submitted:

I think this tread have to be into the MODx project ( http://tracker.modx.com/projects/revo )
Could anybody move it?

**Comment by TriAnMan** [comment]
trianman submitted:

Have made patch for this bug: https://github.com/modxcms/revolution/pull/462

**Comment by opengeek** [comment]
opengeek submitted:

Not having a compound index on the tmplvarid and contentid fields in modTemplateVarResource is causing extremely slow queries on larger datasets, especially with older versions of MySQL. Adding this index improves efficiency of many TV related queries in the core on all versions of MySQL.

**Comment by opengeek** [comment]
opengeek submitted:

See https://github.com/modxcms/revolution/commit/63f45d35dcf39bcf2847567cdd20c4f82c2de44a for commit details
