### ISSUE TITLE
$modx->error is null in modObjectCreateProcessor

### ISSUE THREAD

**Issue by argnist** [modxbot/migrate#9224]
argnist created Redmine issue ID 9224

After updating to modx 2.2.6 I noticed that extra CronManager didn't work. After debugging through my code I passed to modObjectCreateProcessor::beforeSet()
It return !$this->hasErrors(); and  public function hasErrors() {
        return $this->modx->error->hasError();
    }
But in this place $this->modx->error is null and I get an error in log:
[2012-12-07 07:31:03](ERROR @ /assets/components/cronmanager/cron.php) Problem getting service error, instance of class modError, from path 
[2012-12-07 07:31:04](ERROR @ /assets/components/cronmanager/cron.php) Could not load class: modError from moderror.

**Comment by argnist** [comment]
argnist submitted:

And directly in browser cron.php return output:
Fatal error: Call to a member function hasError() on a non-object in ***modx/core/model/modx/modprocessor.class.php on line 119

**Comment by argnist** [comment]
argnist submitted:

I added $this->modx->getService('error', 'error.modError'); in my processor beforeSet() to create modx->error but why it isn't created by that point?

**Comment by opengeek** [comment]
opengeek submitted:

This is unfortunately a side-effect of another bug fix: [#9029] Remove modRequest->loadErrorHandler dependency in runProcessor

This was an invalid dependency on having a modRequest object in order to use runProcessor, which was being used to populate the error service. But when you are not using MODX for request handling, this may not be appropriate. This dependency was removed and any external scripts which do not use a modRequest instance may be affected. Simply calling this after initializing a context in your script should solve the issue, e.g.

<pre>
$modx = new modX();
$modx->initialize('web');
$modx->getService('error', 'error.modError');
</pre>
