### ISSUE TITLE
ResourceMap empty on SQL Server installation

### ISSUE THREAD

**Issue by javadecaf** [modxbot/migrate#9901]
javadecaf created Redmine issue ID 9901

This issue appears to be the result of a defective SQL query in the getResourceCacheMapStmt() method in /core/modx/sqlsrv/modcontext.class.php (which also seems to lack error handling, since the error isn't logged.)  Using xDebug, I pulled the SQL query from this function.  Since it uses bindings, I had to substitute the name of the context manually, but otherwise this is exactly as I retrieved the query from the variables window just before the call to execute():
@SELECT [r].[id], [r].[parent], [r].[uri] FROM [modx_site_content] [r] LEFT JOIN [modx_context_resource] [cr] ON [cr].[context_key] = 'web' AND [r].[id] = [cr].[resource] WHERE [r].[id] != [r].[parent] AND ([r].[context_key] = 'web' OR [cr].[context_key] IS NOT NULL) AND [r].[deleted] = 0 GROUP BY [r].[id], [r].[parent], [r].[uri] ORDER BY [r].[parent] ASC, [r].[menuindex] ASC
@
Running this query in SQL Server Management Studio produced the following error:
@Msg 8127, Level 16, State 1, Line 2
Column "modx_site_content.menuindex" is invalid in the ORDER BY clause because it is not contained in either an aggregate function or the GROUP BY clause.
@
This error in the query appears to be caused by the fact that, for whatever reason, the getSelectColumns statement called for modResource on line 18 does not retrieve 'menuindex' as one of the columns to be selected.  To prove this hypothesis and create a temporary fix, I revised line 20 to read as follows:
@$sql = "SELECT {$resourceCols} FROM {$tblResource} [r] LEFT JOIN {$tblContextResource} [cr] ON [r].[id] = [cr].[resource] WHERE [r].[id] != [r].[parent] AND ([r].[context_key] = ? OR [cr].[context_key] IS NOT NULL) AND [r].[deleted] = 0 GROUP BY {$resourceCols}, menuindex ORDER BY [r].[parent] ASC, [r].[menuindex] ASC";@
After adding this line and clearing the cache, the resourceMap() was no longer blank, and Wayfinder started working properly.

**Comment by ttyiav** [comment]
ttyiav submitted:

Logged in to report exactly the same issue from MODX 2.2.5, which I corrected in-house. Since Wayfinder snippet is very popular and this bug is actually the showstopper for MSSQL installations, I had to act immediately and fix it by "modifying the core" :(

1) First of all, according to T-SQL documentation, "the ORDER BY clause can include items that do not appear in the select list. However, if SELECT DISTINCT is specified, or if the statement contains a GROUP BY clause, or if the SELECT statement contains a UNION operator, the sort columns must appear in the select list."
http://msdn.microsoft.com/en-US/library/ms188385(v=sql.105).aspx

2) Second, after analysis of the query in question and assuming that the idea behind the query is correct:
a) I don't see any reason **to perform the table join** with 'modx_context_resource' at all, as in this query,
because of the 'OR [cr].[context_key] IS NOT NULL' condition and equality of the [r] and [cr] 'context_key' bindings.
The query will select matching rows ([cr].[context_key] implicitly matches [r].[context_key], [r].[id] explicitly matches [cr].[resource]) from 'modx_site_content' whether it has corresponding row in 'modx_context_resource' or not (the OR).

b) Because the 'modx_context_resource' table has compound full row primary key, the GROUP BY in the query is not needed too. It is either 1:1 match or 1:0 mismatch without any duplicates.

3) Therefore, the query, in my opinion, becomes simple one-table filtering in right order.

SELECT [r].[id], [r].[parent], [r].[uri]
FROM [modx_site_content] [r] 
WHERE [r].[id] != [r].[parent] 
AND [r].[context_key] = '<context_key>'
AND [r].[deleted] = 0 
ORDER BY [r].[parent] ASC, [r].[menuindex] ASC
